### Issue token
POST {{artel_url}}/token
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate, br, zstd

grant_type = authorization_code &
code = 4593f8bcde194b577906e9a932fb2a06 &
client_id = 33b343b2f1911f76160442ece36ba2d6 &
code_verifier = 30RO__Sm98GzGISwG84JwRG-S77eoe8uqgI6NoK7RJThUswmAZ_9LL-wWwGbCpwxoI6uUjVxMzg_og3AO4IXYb7z1lFbPXJkcF5Y0JD4h40XKg7NT_CU6xuQ2mXVawhW &
redirect_uri = https%3A%2F%2Fclaude.ai%2Fapi%2Fmcp%2Fauth_callback &
resource = https%3A%2F%2Fartel-alexskilled.redsock.ru%2Fmcp

### Initialize
POST {{artel_url}}/mcp
Content-Type: application/json
Authorization: Bearer artel_vtk_3d8178b3c8364a9cb7181b11575734e5_ca95efba88f40da657f8113420fb63cd

{
  "method": "initialize",
  "params": {
    "protocolVersion": "2025-11-25",
    "capabilities": {
      "extensions": {
        "io.modelcontextprotocol/ui": {
          "mimeTypes": [
            "text/html;profile=mcp-app"
          ]
        }
      }
    },
    "clientInfo": {
      "name": "Anthropic/ClaudeAI",
      "version": "1.0.0"
    }
  },
  "jsonrpc": "2.0",
  "id": 0
}