### Create MCP Key
POST {{artel_url}}/api/mcp/bd962f5b-a8c5-48b3-b54d-9c0d9c9b47ca/mcp-keys
Content-Type: application/json
Authorization: {{auth_token}}

{
  "name": "alex-skilled-key"
}

###artel_vtk_08d0af24287a481d8dde9c629905efb9_e30f50eb966a2e99c059d76a5b55374b

### List MCP Keys
GET {{artel_url}}/api/mcp/f5cf9ccf-947a-4347-8fa4-2ef12d120646/mcp-keys
Authorization: {{auth_token}}

### Revoke MCP Key
DELETE {{artel_url}}/api/mcp/{{vault_id}}/mcp-keys/{{mcp_key_id}}
Authorization: {{auth_token}}
