services:
  artel-couchdb:
    image: apache/couchdb:3
    container_name: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
      COUCHDB_NODENAME: nonode@nohost
    ports:
      - "15984:5984"
    volumes:
      - ./local_data/couch:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5984/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  artel-garage-s3:
    image: dxflrs/garage:v2.3.0
    container_name: artel-garage-s3
    ports:
      - "13900:3900" # S3 API
      - "13901:3901" # RPC (cluster/layout management)
      - "13902:3902" # Web
      - "13903:3903" # Admin API
    volumes:
      - ./.verv/template/garage.toml:/etc/garage.toml:ro
      - ./local_data/garage/meta:/var/lib/garage/meta
      - ./local_data/garage/data:/var/lib/garage/data
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  artel-db:
    image: postgres:18
    environment:
      POSTGRES_USER: artel
      POSTGRES_PASSWORD:
      POSTGRES_DB: artel_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '15433:5432'
    volumes:
      - ./local_data/pg:/var/lib/postgresql