// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: admin_users.proto

package artel_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminUsersAPI_ListArtelUsers_FullMethodName  = "/artel_admin_users.AdminUsersAPI/ListArtelUsers"
	AdminUsersAPI_GetArtelUser_FullMethodName    = "/artel_admin_users.AdminUsersAPI/GetArtelUser"
	AdminUsersAPI_GetUserSessions_FullMethodName = "/artel_admin_users.AdminUsersAPI/GetUserSessions"
)

// AdminUsersAPIClient is the client API for AdminUsersAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminUsersAPIClient interface {
	ListArtelUsers(ctx context.Context, in *ListArtelUsers_Request, opts ...grpc.CallOption) (*ListArtelUsers_Response, error)
	GetArtelUser(ctx context.Context, in *GetArtelUser_Request, opts ...grpc.CallOption) (*GetArtelUser_Response, error)
	GetUserSessions(ctx context.Context, in *GetUserSessions_Request, opts ...grpc.CallOption) (*GetUserSessions_Response, error)
}

type adminUsersAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminUsersAPIClient(cc grpc.ClientConnInterface) AdminUsersAPIClient {
	return &adminUsersAPIClient{cc}
}

func (c *adminUsersAPIClient) ListArtelUsers(ctx context.Context, in *ListArtelUsers_Request, opts ...grpc.CallOption) (*ListArtelUsers_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArtelUsers_Response)
	err := c.cc.Invoke(ctx, AdminUsersAPI_ListArtelUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUsersAPIClient) GetArtelUser(ctx context.Context, in *GetArtelUser_Request, opts ...grpc.CallOption) (*GetArtelUser_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArtelUser_Response)
	err := c.cc.Invoke(ctx, AdminUsersAPI_GetArtelUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUsersAPIClient) GetUserSessions(ctx context.Context, in *GetUserSessions_Request, opts ...grpc.CallOption) (*GetUserSessions_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSessions_Response)
	err := c.cc.Invoke(ctx, AdminUsersAPI_GetUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminUsersAPIServer is the server API for AdminUsersAPI service.
// All implementations must embed UnimplementedAdminUsersAPIServer
// for forward compatibility.
type AdminUsersAPIServer interface {
	ListArtelUsers(context.Context, *ListArtelUsers_Request) (*ListArtelUsers_Response, error)
	GetArtelUser(context.Context, *GetArtelUser_Request) (*GetArtelUser_Response, error)
	GetUserSessions(context.Context, *GetUserSessions_Request) (*GetUserSessions_Response, error)
	mustEmbedUnimplementedAdminUsersAPIServer()
}

// UnimplementedAdminUsersAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminUsersAPIServer struct{}

func (UnimplementedAdminUsersAPIServer) ListArtelUsers(context.Context, *ListArtelUsers_Request) (*ListArtelUsers_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtelUsers not implemented")
}
func (UnimplementedAdminUsersAPIServer) GetArtelUser(context.Context, *GetArtelUser_Request) (*GetArtelUser_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArtelUser not implemented")
}
func (UnimplementedAdminUsersAPIServer) GetUserSessions(context.Context, *GetUserSessions_Request) (*GetUserSessions_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSessions not implemented")
}
func (UnimplementedAdminUsersAPIServer) mustEmbedUnimplementedAdminUsersAPIServer() {}
func (UnimplementedAdminUsersAPIServer) testEmbeddedByValue()                       {}

// UnsafeAdminUsersAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminUsersAPIServer will
// result in compilation errors.
type UnsafeAdminUsersAPIServer interface {
	mustEmbedUnimplementedAdminUsersAPIServer()
}

func RegisterAdminUsersAPIServer(s grpc.ServiceRegistrar, srv AdminUsersAPIServer) {
	// If the following call panics, it indicates UnimplementedAdminUsersAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminUsersAPI_ServiceDesc, srv)
}

func _AdminUsersAPI_ListArtelUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtelUsers_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUsersAPIServer).ListArtelUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUsersAPI_ListArtelUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUsersAPIServer).ListArtelUsers(ctx, req.(*ListArtelUsers_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUsersAPI_GetArtelUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtelUser_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUsersAPIServer).GetArtelUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUsersAPI_GetArtelUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUsersAPIServer).GetArtelUser(ctx, req.(*GetArtelUser_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminUsersAPI_GetUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSessions_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminUsersAPIServer).GetUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminUsersAPI_GetUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminUsersAPIServer).GetUserSessions(ctx, req.(*GetUserSessions_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminUsersAPI_ServiceDesc is the grpc.ServiceDesc for AdminUsersAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminUsersAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artel_admin_users.AdminUsersAPI",
	HandlerType: (*AdminUsersAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArtelUsers",
			Handler:    _AdminUsersAPI_ListArtelUsers_Handler,
		},
		{
			MethodName: "GetArtelUser",
			Handler:    _AdminUsersAPI_GetArtelUser_Handler,
		},
		{
			MethodName: "GetUserSessions",
			Handler:    _AdminUsersAPI_GetUserSessions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_users.proto",
}
