// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: admin_system_settings.proto

package artel_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettings) Reset() {
	*x = GetSettings{}
	mi := &file_admin_system_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettings) ProtoMessage() {}

func (x *GetSettings) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettings.ProtoReflect.Descriptor instead.
func (*GetSettings) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{0}
}

type UpdateSystemPrompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemPrompt) Reset() {
	*x = UpdateSystemPrompt{}
	mi := &file_admin_system_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemPrompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemPrompt) ProtoMessage() {}

func (x *UpdateSystemPrompt) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemPrompt.ProtoReflect.Descriptor instead.
func (*UpdateSystemPrompt) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{1}
}

type UpdateAuthMethods struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthMethods) Reset() {
	*x = UpdateAuthMethods{}
	mi := &file_admin_system_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthMethods) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthMethods) ProtoMessage() {}

func (x *UpdateAuthMethods) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthMethods.ProtoReflect.Descriptor instead.
func (*UpdateAuthMethods) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{2}
}

type UpdateRegistrationMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegistrationMode) Reset() {
	*x = UpdateRegistrationMode{}
	mi := &file_admin_system_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegistrationMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistrationMode) ProtoMessage() {}

func (x *UpdateRegistrationMode) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistrationMode.ProtoReflect.Descriptor instead.
func (*UpdateRegistrationMode) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{3}
}

type UpdateDefaultDocsVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefaultDocsVault) Reset() {
	*x = UpdateDefaultDocsVault{}
	mi := &file_admin_system_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefaultDocsVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultDocsVault) ProtoMessage() {}

func (x *UpdateDefaultDocsVault) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultDocsVault.ProtoReflect.Descriptor instead.
func (*UpdateDefaultDocsVault) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{4}
}

type GetSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettings_Request) Reset() {
	*x = GetSettings_Request{}
	mi := &file_admin_system_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettings_Request) ProtoMessage() {}

func (x *GetSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettings_Request.ProtoReflect.Descriptor instead.
func (*GetSettings_Request) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{0, 0}
}

type GetSettings_Response struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PasswordAuthEnabled bool                   `protobuf:"varint,1,opt,name=password_auth_enabled,json=passwordAuthEnabled,proto3" json:"password_auth_enabled,omitempty"`
	TelegramAuthEnabled bool                   `protobuf:"varint,2,opt,name=telegram_auth_enabled,json=telegramAuthEnabled,proto3" json:"telegram_auth_enabled,omitempty"`
	RegistrationMode    RegistrationMode       `protobuf:"varint,3,opt,name=registration_mode,json=registrationMode,proto3,enum=artel_setup_wizard.RegistrationMode" json:"registration_mode,omitempty"`
	// default_docs_vault_id/_name/_slug are all empty strings when no default docs vault is
	// configured.
	DefaultDocsVaultId   string     `protobuf:"bytes,4,opt,name=default_docs_vault_id,json=defaultDocsVaultId,proto3" json:"default_docs_vault_id,omitempty"`
	DefaultDocsVaultName string     `protobuf:"bytes,5,opt,name=default_docs_vault_name,json=defaultDocsVaultName,proto3" json:"default_docs_vault_name,omitempty"`
	DefaultDocsVaultSlug string     `protobuf:"bytes,6,opt,name=default_docs_vault_slug,json=defaultDocsVaultSlug,proto3" json:"default_docs_vault_slug,omitempty"`
	DefaultDocsSource    DocsSource `protobuf:"varint,7,opt,name=default_docs_source,json=defaultDocsSource,proto3,enum=artel_public_docs.DocsSource" json:"default_docs_source,omitempty"`
	SystemPrompt         string     `protobuf:"bytes,8,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetSettings_Response) Reset() {
	*x = GetSettings_Response{}
	mi := &file_admin_system_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettings_Response) ProtoMessage() {}

func (x *GetSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettings_Response.ProtoReflect.Descriptor instead.
func (*GetSettings_Response) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetSettings_Response) GetPasswordAuthEnabled() bool {
	if x != nil {
		return x.PasswordAuthEnabled
	}
	return false
}

func (x *GetSettings_Response) GetTelegramAuthEnabled() bool {
	if x != nil {
		return x.TelegramAuthEnabled
	}
	return false
}

func (x *GetSettings_Response) GetRegistrationMode() RegistrationMode {
	if x != nil {
		return x.RegistrationMode
	}
	return RegistrationMode_ADMIN_ONLY
}

func (x *GetSettings_Response) GetDefaultDocsVaultId() string {
	if x != nil {
		return x.DefaultDocsVaultId
	}
	return ""
}

func (x *GetSettings_Response) GetDefaultDocsVaultName() string {
	if x != nil {
		return x.DefaultDocsVaultName
	}
	return ""
}

func (x *GetSettings_Response) GetDefaultDocsVaultSlug() string {
	if x != nil {
		return x.DefaultDocsVaultSlug
	}
	return ""
}

func (x *GetSettings_Response) GetDefaultDocsSource() DocsSource {
	if x != nil {
		return x.DefaultDocsSource
	}
	return DocsSource_VAULT
}

func (x *GetSettings_Response) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

type UpdateSystemPrompt_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemPrompt_Request) Reset() {
	*x = UpdateSystemPrompt_Request{}
	mi := &file_admin_system_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemPrompt_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemPrompt_Request) ProtoMessage() {}

func (x *UpdateSystemPrompt_Request) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemPrompt_Request.ProtoReflect.Descriptor instead.
func (*UpdateSystemPrompt_Request) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UpdateSystemPrompt_Request) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type UpdateSystemPrompt_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemPrompt_Response) Reset() {
	*x = UpdateSystemPrompt_Response{}
	mi := &file_admin_system_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemPrompt_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemPrompt_Response) ProtoMessage() {}

func (x *UpdateSystemPrompt_Response) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemPrompt_Response.ProtoReflect.Descriptor instead.
func (*UpdateSystemPrompt_Response) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{1, 1}
}

type UpdateAuthMethods_Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PasswordEnabled bool                   `protobuf:"varint,1,opt,name=password_enabled,json=passwordEnabled,proto3" json:"password_enabled,omitempty"`
	TelegramEnabled bool                   `protobuf:"varint,2,opt,name=telegram_enabled,json=telegramEnabled,proto3" json:"telegram_enabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateAuthMethods_Request) Reset() {
	*x = UpdateAuthMethods_Request{}
	mi := &file_admin_system_settings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthMethods_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthMethods_Request) ProtoMessage() {}

func (x *UpdateAuthMethods_Request) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthMethods_Request.ProtoReflect.Descriptor instead.
func (*UpdateAuthMethods_Request) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UpdateAuthMethods_Request) GetPasswordEnabled() bool {
	if x != nil {
		return x.PasswordEnabled
	}
	return false
}

func (x *UpdateAuthMethods_Request) GetTelegramEnabled() bool {
	if x != nil {
		return x.TelegramEnabled
	}
	return false
}

type UpdateAuthMethods_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuthMethods_Response) Reset() {
	*x = UpdateAuthMethods_Response{}
	mi := &file_admin_system_settings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuthMethods_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuthMethods_Response) ProtoMessage() {}

func (x *UpdateAuthMethods_Response) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuthMethods_Response.ProtoReflect.Descriptor instead.
func (*UpdateAuthMethods_Response) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{2, 1}
}

type UpdateRegistrationMode_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          RegistrationMode       `protobuf:"varint,1,opt,name=mode,proto3,enum=artel_setup_wizard.RegistrationMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegistrationMode_Request) Reset() {
	*x = UpdateRegistrationMode_Request{}
	mi := &file_admin_system_settings_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegistrationMode_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistrationMode_Request) ProtoMessage() {}

func (x *UpdateRegistrationMode_Request) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistrationMode_Request.ProtoReflect.Descriptor instead.
func (*UpdateRegistrationMode_Request) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UpdateRegistrationMode_Request) GetMode() RegistrationMode {
	if x != nil {
		return x.Mode
	}
	return RegistrationMode_ADMIN_ONLY
}

type UpdateRegistrationMode_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRegistrationMode_Response) Reset() {
	*x = UpdateRegistrationMode_Response{}
	mi := &file_admin_system_settings_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRegistrationMode_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistrationMode_Response) ProtoMessage() {}

func (x *UpdateRegistrationMode_Response) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistrationMode_Response.ProtoReflect.Descriptor instead.
func (*UpdateRegistrationMode_Response) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{3, 1}
}

type UpdateDefaultDocsVault_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Source        DocsSource             `protobuf:"varint,2,opt,name=source,proto3,enum=artel_public_docs.DocsSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefaultDocsVault_Request) Reset() {
	*x = UpdateDefaultDocsVault_Request{}
	mi := &file_admin_system_settings_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefaultDocsVault_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultDocsVault_Request) ProtoMessage() {}

func (x *UpdateDefaultDocsVault_Request) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultDocsVault_Request.ProtoReflect.Descriptor instead.
func (*UpdateDefaultDocsVault_Request) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateDefaultDocsVault_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *UpdateDefaultDocsVault_Request) GetSource() DocsSource {
	if x != nil {
		return x.Source
	}
	return DocsSource_VAULT
}

type UpdateDefaultDocsVault_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDefaultDocsVault_Response) Reset() {
	*x = UpdateDefaultDocsVault_Response{}
	mi := &file_admin_system_settings_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDefaultDocsVault_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultDocsVault_Response) ProtoMessage() {}

func (x *UpdateDefaultDocsVault_Response) ProtoReflect() protoreflect.Message {
	mi := &file_admin_system_settings_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultDocsVault_Response.ProtoReflect.Descriptor instead.
func (*UpdateDefaultDocsVault_Response) Descriptor() ([]byte, []int) {
	return file_admin_system_settings_proto_rawDescGZIP(), []int{4, 1}
}

var File_admin_system_settings_proto protoreflect.FileDescriptor

const file_admin_system_settings_proto_rawDesc = "" +
	"\n" +
	"\x1badmin_system_settings.proto\x12\x1bartel_admin_system_settings\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\x1a\x11public_docs.proto\x1a\x12setup_wizard.proto\"\xf5\x03\n" +
	"\vGetSettings\x1a\t\n" +
	"\aRequest\x1a\xda\x03\n" +
	"\bResponse\x122\n" +
	"\x15password_auth_enabled\x18\x01 \x01(\bR\x13passwordAuthEnabled\x122\n" +
	"\x15telegram_auth_enabled\x18\x02 \x01(\bR\x13telegramAuthEnabled\x12Q\n" +
	"\x11registration_mode\x18\x03 \x01(\x0e2$.artel_setup_wizard.RegistrationModeR\x10registrationMode\x121\n" +
	"\x15default_docs_vault_id\x18\x04 \x01(\tR\x12defaultDocsVaultId\x125\n" +
	"\x17default_docs_vault_name\x18\x05 \x01(\tR\x14defaultDocsVaultName\x125\n" +
	"\x17default_docs_vault_slug\x18\x06 \x01(\tR\x14defaultDocsVaultSlug\x12M\n" +
	"\x13default_docs_source\x18\a \x01(\x0e2\x1d.artel_public_docs.DocsSourceR\x11defaultDocsSource\x12#\n" +
	"\rsystem_prompt\x18\b \x01(\tR\fsystemPrompt\"C\n" +
	"\x12UpdateSystemPrompt\x1a!\n" +
	"\aRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x1a\n" +
	"\n" +
	"\bResponse\"\x80\x01\n" +
	"\x11UpdateAuthMethods\x1a_\n" +
	"\aRequest\x12)\n" +
	"\x10password_enabled\x18\x01 \x01(\bR\x0fpasswordEnabled\x12)\n" +
	"\x10telegram_enabled\x18\x02 \x01(\bR\x0ftelegramEnabled\x1a\n" +
	"\n" +
	"\bResponse\"i\n" +
	"\x16UpdateRegistrationMode\x1aC\n" +
	"\aRequest\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.artel_setup_wizard.RegistrationModeR\x04mode\x1a\n" +
	"\n" +
	"\bResponse\"\x81\x01\n" +
	"\x16UpdateDefaultDocsVault\x1a[\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x125\n" +
	"\x06source\x18\x02 \x01(\x0e2\x1d.artel_public_docs.DocsSourceR\x06source\x1a\n" +
	"\n" +
	"\bResponse2\xed\a\n" +
	"\x16AdminSystemSettingsAPI\x12\x9d\x01\n" +
	"\vGetSettings\x120.artel_admin_system_settings.GetSettings.Request\x1a1.artel_admin_system_settings.GetSettings.Response\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/admin_system_settings/get\x12\xbf\x01\n" +
	"\x11UpdateAuthMethods\x126.artel_admin_system_settings.UpdateAuthMethods.Request\x1a7.artel_admin_system_settings.UpdateAuthMethods.Response\"9\x82\xd3\xe4\x93\x023:\x01*\"./api/admin_system_settings/update_auth_methods\x12\xd3\x01\n" +
	"\x16UpdateRegistrationMode\x12;.artel_admin_system_settings.UpdateRegistrationMode.Request\x1a<.artel_admin_system_settings.UpdateRegistrationMode.Response\">\x82\xd3\xe4\x93\x028:\x01*\"3/api/admin_system_settings/update_registration_mode\x12\xd4\x01\n" +
	"\x16UpdateDefaultDocsVault\x12;.artel_admin_system_settings.UpdateDefaultDocsVault.Request\x1a<.artel_admin_system_settings.UpdateDefaultDocsVault.Response\"?\x82\xd3\xe4\x93\x029:\x01*\"4/api/admin_system_settings/update_default_docs_vault\x12\xc3\x01\n" +
	"\x12UpdateSystemPrompt\x127.artel_admin_system_settings.UpdateSystemPrompt.Request\x1a8.artel_admin_system_settings.UpdateSystemPrompt.Response\":\x82\xd3\xe4\x93\x024:\x01*\"//api/admin_system_settings/update_system_promptB\x1a\x92\x82\x19\n" +
	"@artel/apiZ\n" +
	"/artel_apib\x06proto3"

var (
	file_admin_system_settings_proto_rawDescOnce sync.Once
	file_admin_system_settings_proto_rawDescData []byte
)

func file_admin_system_settings_proto_rawDescGZIP() []byte {
	file_admin_system_settings_proto_rawDescOnce.Do(func() {
		file_admin_system_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_system_settings_proto_rawDesc), len(file_admin_system_settings_proto_rawDesc)))
	})
	return file_admin_system_settings_proto_rawDescData
}

var file_admin_system_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_admin_system_settings_proto_goTypes = []any{
	(*GetSettings)(nil),                     // 0: artel_admin_system_settings.GetSettings
	(*UpdateSystemPrompt)(nil),              // 1: artel_admin_system_settings.UpdateSystemPrompt
	(*UpdateAuthMethods)(nil),               // 2: artel_admin_system_settings.UpdateAuthMethods
	(*UpdateRegistrationMode)(nil),          // 3: artel_admin_system_settings.UpdateRegistrationMode
	(*UpdateDefaultDocsVault)(nil),          // 4: artel_admin_system_settings.UpdateDefaultDocsVault
	(*GetSettings_Request)(nil),             // 5: artel_admin_system_settings.GetSettings.Request
	(*GetSettings_Response)(nil),            // 6: artel_admin_system_settings.GetSettings.Response
	(*UpdateSystemPrompt_Request)(nil),      // 7: artel_admin_system_settings.UpdateSystemPrompt.Request
	(*UpdateSystemPrompt_Response)(nil),     // 8: artel_admin_system_settings.UpdateSystemPrompt.Response
	(*UpdateAuthMethods_Request)(nil),       // 9: artel_admin_system_settings.UpdateAuthMethods.Request
	(*UpdateAuthMethods_Response)(nil),      // 10: artel_admin_system_settings.UpdateAuthMethods.Response
	(*UpdateRegistrationMode_Request)(nil),  // 11: artel_admin_system_settings.UpdateRegistrationMode.Request
	(*UpdateRegistrationMode_Response)(nil), // 12: artel_admin_system_settings.UpdateRegistrationMode.Response
	(*UpdateDefaultDocsVault_Request)(nil),  // 13: artel_admin_system_settings.UpdateDefaultDocsVault.Request
	(*UpdateDefaultDocsVault_Response)(nil), // 14: artel_admin_system_settings.UpdateDefaultDocsVault.Response
	(RegistrationMode)(0),                   // 15: artel_setup_wizard.RegistrationMode
	(DocsSource)(0),                         // 16: artel_public_docs.DocsSource
}
var file_admin_system_settings_proto_depIdxs = []int32{
	15, // 0: artel_admin_system_settings.GetSettings.Response.registration_mode:type_name -> artel_setup_wizard.RegistrationMode
	16, // 1: artel_admin_system_settings.GetSettings.Response.default_docs_source:type_name -> artel_public_docs.DocsSource
	15, // 2: artel_admin_system_settings.UpdateRegistrationMode.Request.mode:type_name -> artel_setup_wizard.RegistrationMode
	16, // 3: artel_admin_system_settings.UpdateDefaultDocsVault.Request.source:type_name -> artel_public_docs.DocsSource
	5,  // 4: artel_admin_system_settings.AdminSystemSettingsAPI.GetSettings:input_type -> artel_admin_system_settings.GetSettings.Request
	9,  // 5: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateAuthMethods:input_type -> artel_admin_system_settings.UpdateAuthMethods.Request
	11, // 6: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateRegistrationMode:input_type -> artel_admin_system_settings.UpdateRegistrationMode.Request
	13, // 7: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateDefaultDocsVault:input_type -> artel_admin_system_settings.UpdateDefaultDocsVault.Request
	7,  // 8: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateSystemPrompt:input_type -> artel_admin_system_settings.UpdateSystemPrompt.Request
	6,  // 9: artel_admin_system_settings.AdminSystemSettingsAPI.GetSettings:output_type -> artel_admin_system_settings.GetSettings.Response
	10, // 10: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateAuthMethods:output_type -> artel_admin_system_settings.UpdateAuthMethods.Response
	12, // 11: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateRegistrationMode:output_type -> artel_admin_system_settings.UpdateRegistrationMode.Response
	14, // 12: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateDefaultDocsVault:output_type -> artel_admin_system_settings.UpdateDefaultDocsVault.Response
	8,  // 13: artel_admin_system_settings.AdminSystemSettingsAPI.UpdateSystemPrompt:output_type -> artel_admin_system_settings.UpdateSystemPrompt.Response
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_admin_system_settings_proto_init() }
func file_admin_system_settings_proto_init() {
	if File_admin_system_settings_proto != nil {
		return
	}
	file_public_docs_proto_init()
	file_setup_wizard_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_system_settings_proto_rawDesc), len(file_admin_system_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_system_settings_proto_goTypes,
		DependencyIndexes: file_admin_system_settings_proto_depIdxs,
		MessageInfos:      file_admin_system_settings_proto_msgTypes,
	}.Build()
	File_admin_system_settings_proto = out.File
	file_admin_system_settings_proto_goTypes = nil
	file_admin_system_settings_proto_depIdxs = nil
}
