// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: external_connections.proto

package artel_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalConnectionsAPI_InitiateGoogleOAuth_FullMethodName         = "/artel_api.ExternalConnectionsAPI/InitiateGoogleOAuth"
	ExternalConnectionsAPI_ListConnections_FullMethodName             = "/artel_api.ExternalConnectionsAPI/ListConnections"
	ExternalConnectionsAPI_DisconnectProvider_FullMethodName          = "/artel_api.ExternalConnectionsAPI/DisconnectProvider"
	ExternalConnectionsAPI_DisconnectConnection_FullMethodName        = "/artel_api.ExternalConnectionsAPI/DisconnectConnection"
	ExternalConnectionsAPI_GetGooglePickerToken_FullMethodName        = "/artel_api.ExternalConnectionsAPI/GetGooglePickerToken"
	ExternalConnectionsAPI_AddSpreadsheet_FullMethodName              = "/artel_api.ExternalConnectionsAPI/AddSpreadsheet"
	ExternalConnectionsAPI_ListSpreadsheets_FullMethodName            = "/artel_api.ExternalConnectionsAPI/ListSpreadsheets"
	ExternalConnectionsAPI_RemoveSpreadsheet_FullMethodName           = "/artel_api.ExternalConnectionsAPI/RemoveSpreadsheet"
	ExternalConnectionsAPI_AddEmailConnection_FullMethodName          = "/artel_api.ExternalConnectionsAPI/AddEmailConnection"
	ExternalConnectionsAPI_CheckEmailConnection_FullMethodName        = "/artel_api.ExternalConnectionsAPI/CheckEmailConnection"
	ExternalConnectionsAPI_ListMailServerSuggestions_FullMethodName   = "/artel_api.ExternalConnectionsAPI/ListMailServerSuggestions"
	ExternalConnectionsAPI_AddGitlabConnection_FullMethodName         = "/artel_api.ExternalConnectionsAPI/AddGitlabConnection"
	ExternalConnectionsAPI_CheckGitlabConnection_FullMethodName       = "/artel_api.ExternalConnectionsAPI/CheckGitlabConnection"
	ExternalConnectionsAPI_GenerateGitlabWebhookSecret_FullMethodName = "/artel_api.ExternalConnectionsAPI/GenerateGitlabWebhookSecret"
	ExternalConnectionsAPI_AddTrelloConnection_FullMethodName         = "/artel_api.ExternalConnectionsAPI/AddTrelloConnection"
	ExternalConnectionsAPI_CheckTrelloConnection_FullMethodName       = "/artel_api.ExternalConnectionsAPI/CheckTrelloConnection"
	ExternalConnectionsAPI_AddTelegramConnection_FullMethodName       = "/artel_api.ExternalConnectionsAPI/AddTelegramConnection"
	ExternalConnectionsAPI_CheckTelegramConnection_FullMethodName     = "/artel_api.ExternalConnectionsAPI/CheckTelegramConnection"
	ExternalConnectionsAPI_AddAnthropicConnection_FullMethodName      = "/artel_api.ExternalConnectionsAPI/AddAnthropicConnection"
	ExternalConnectionsAPI_CheckAnthropicConnection_FullMethodName    = "/artel_api.ExternalConnectionsAPI/CheckAnthropicConnection"
	ExternalConnectionsAPI_AddGenericConnection_FullMethodName        = "/artel_api.ExternalConnectionsAPI/AddGenericConnection"
)

// ExternalConnectionsAPIClient is the client API for ExternalConnectionsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalConnectionsAPIClient interface {
	InitiateGoogleOAuth(ctx context.Context, in *InitiateGoogleOAuth_Request, opts ...grpc.CallOption) (*InitiateGoogleOAuth_Response, error)
	ListConnections(ctx context.Context, in *ListConnections_Request, opts ...grpc.CallOption) (*ListConnections_Response, error)
	DisconnectProvider(ctx context.Context, in *DisconnectProvider_Request, opts ...grpc.CallOption) (*DisconnectProvider_Response, error)
	// DisconnectConnection removes a single connection by id, for providers (like Trello) that can
	// hold more than one connection per user — DisconnectProvider removes the sole connection for a
	// single-connection provider instead.
	DisconnectConnection(ctx context.Context, in *DisconnectConnection_Request, opts ...grpc.CallOption) (*DisconnectConnection_Response, error)
	GetGooglePickerToken(ctx context.Context, in *GooglePickerToken_Request, opts ...grpc.CallOption) (*GooglePickerToken_Response, error)
	AddSpreadsheet(ctx context.Context, in *AddSpreadsheet_Request, opts ...grpc.CallOption) (*AddSpreadsheet_Response, error)
	ListSpreadsheets(ctx context.Context, in *ListSpreadsheets_Request, opts ...grpc.CallOption) (*ListSpreadsheets_Response, error)
	RemoveSpreadsheet(ctx context.Context, in *RemoveSpreadsheet_Request, opts ...grpc.CallOption) (*RemoveSpreadsheet_Response, error)
	AddEmailConnection(ctx context.Context, in *AddEmailConnection_Request, opts ...grpc.CallOption) (*AddEmailConnection_Response, error)
	CheckEmailConnection(ctx context.Context, in *CheckEmailConnection_Request, opts ...grpc.CallOption) (*CheckEmailConnection_Response, error)
	ListMailServerSuggestions(ctx context.Context, in *ListMailServerSuggestions_Request, opts ...grpc.CallOption) (*ListMailServerSuggestions_Response, error)
	AddGitlabConnection(ctx context.Context, in *AddGitlabConnection_Request, opts ...grpc.CallOption) (*AddGitlabConnection_Response, error)
	CheckGitlabConnection(ctx context.Context, in *CheckGitlabConnection_Request, opts ...grpc.CallOption) (*CheckGitlabConnection_Response, error)
	GenerateGitlabWebhookSecret(ctx context.Context, in *GenerateGitlabWebhookSecret_Request, opts ...grpc.CallOption) (*GenerateGitlabWebhookSecret_Response, error)
	AddTrelloConnection(ctx context.Context, in *AddTrelloConnection_Request, opts ...grpc.CallOption) (*AddTrelloConnection_Response, error)
	CheckTrelloConnection(ctx context.Context, in *CheckTrelloConnection_Request, opts ...grpc.CallOption) (*CheckTrelloConnection_Response, error)
	AddTelegramConnection(ctx context.Context, in *AddTelegramConnection_Request, opts ...grpc.CallOption) (*AddTelegramConnection_Response, error)
	CheckTelegramConnection(ctx context.Context, in *CheckTelegramConnection_Request, opts ...grpc.CallOption) (*CheckTelegramConnection_Response, error)
	AddAnthropicConnection(ctx context.Context, in *AddAnthropicConnection_Request, opts ...grpc.CallOption) (*AddAnthropicConnection_Response, error)
	CheckAnthropicConnection(ctx context.Context, in *CheckAnthropicConnection_Request, opts ...grpc.CallOption) (*CheckAnthropicConnection_Response, error)
	AddGenericConnection(ctx context.Context, in *AddGenericConnection_Request, opts ...grpc.CallOption) (*AddGenericConnection_Response, error)
}

type externalConnectionsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalConnectionsAPIClient(cc grpc.ClientConnInterface) ExternalConnectionsAPIClient {
	return &externalConnectionsAPIClient{cc}
}

func (c *externalConnectionsAPIClient) InitiateGoogleOAuth(ctx context.Context, in *InitiateGoogleOAuth_Request, opts ...grpc.CallOption) (*InitiateGoogleOAuth_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateGoogleOAuth_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_InitiateGoogleOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) ListConnections(ctx context.Context, in *ListConnections_Request, opts ...grpc.CallOption) (*ListConnections_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnections_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) DisconnectProvider(ctx context.Context, in *DisconnectProvider_Request, opts ...grpc.CallOption) (*DisconnectProvider_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectProvider_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_DisconnectProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) DisconnectConnection(ctx context.Context, in *DisconnectConnection_Request, opts ...grpc.CallOption) (*DisconnectConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_DisconnectConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) GetGooglePickerToken(ctx context.Context, in *GooglePickerToken_Request, opts ...grpc.CallOption) (*GooglePickerToken_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GooglePickerToken_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_GetGooglePickerToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) AddSpreadsheet(ctx context.Context, in *AddSpreadsheet_Request, opts ...grpc.CallOption) (*AddSpreadsheet_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSpreadsheet_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_AddSpreadsheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) ListSpreadsheets(ctx context.Context, in *ListSpreadsheets_Request, opts ...grpc.CallOption) (*ListSpreadsheets_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpreadsheets_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_ListSpreadsheets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) RemoveSpreadsheet(ctx context.Context, in *RemoveSpreadsheet_Request, opts ...grpc.CallOption) (*RemoveSpreadsheet_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSpreadsheet_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_RemoveSpreadsheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) AddEmailConnection(ctx context.Context, in *AddEmailConnection_Request, opts ...grpc.CallOption) (*AddEmailConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEmailConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_AddEmailConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) CheckEmailConnection(ctx context.Context, in *CheckEmailConnection_Request, opts ...grpc.CallOption) (*CheckEmailConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEmailConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_CheckEmailConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) ListMailServerSuggestions(ctx context.Context, in *ListMailServerSuggestions_Request, opts ...grpc.CallOption) (*ListMailServerSuggestions_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMailServerSuggestions_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_ListMailServerSuggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) AddGitlabConnection(ctx context.Context, in *AddGitlabConnection_Request, opts ...grpc.CallOption) (*AddGitlabConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGitlabConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_AddGitlabConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) CheckGitlabConnection(ctx context.Context, in *CheckGitlabConnection_Request, opts ...grpc.CallOption) (*CheckGitlabConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckGitlabConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_CheckGitlabConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) GenerateGitlabWebhookSecret(ctx context.Context, in *GenerateGitlabWebhookSecret_Request, opts ...grpc.CallOption) (*GenerateGitlabWebhookSecret_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateGitlabWebhookSecret_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_GenerateGitlabWebhookSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) AddTrelloConnection(ctx context.Context, in *AddTrelloConnection_Request, opts ...grpc.CallOption) (*AddTrelloConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTrelloConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_AddTrelloConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) CheckTrelloConnection(ctx context.Context, in *CheckTrelloConnection_Request, opts ...grpc.CallOption) (*CheckTrelloConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTrelloConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_CheckTrelloConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) AddTelegramConnection(ctx context.Context, in *AddTelegramConnection_Request, opts ...grpc.CallOption) (*AddTelegramConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTelegramConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_AddTelegramConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) CheckTelegramConnection(ctx context.Context, in *CheckTelegramConnection_Request, opts ...grpc.CallOption) (*CheckTelegramConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTelegramConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_CheckTelegramConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) AddAnthropicConnection(ctx context.Context, in *AddAnthropicConnection_Request, opts ...grpc.CallOption) (*AddAnthropicConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAnthropicConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_AddAnthropicConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) CheckAnthropicConnection(ctx context.Context, in *CheckAnthropicConnection_Request, opts ...grpc.CallOption) (*CheckAnthropicConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAnthropicConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_CheckAnthropicConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalConnectionsAPIClient) AddGenericConnection(ctx context.Context, in *AddGenericConnection_Request, opts ...grpc.CallOption) (*AddGenericConnection_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGenericConnection_Response)
	err := c.cc.Invoke(ctx, ExternalConnectionsAPI_AddGenericConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalConnectionsAPIServer is the server API for ExternalConnectionsAPI service.
// All implementations must embed UnimplementedExternalConnectionsAPIServer
// for forward compatibility.
type ExternalConnectionsAPIServer interface {
	InitiateGoogleOAuth(context.Context, *InitiateGoogleOAuth_Request) (*InitiateGoogleOAuth_Response, error)
	ListConnections(context.Context, *ListConnections_Request) (*ListConnections_Response, error)
	DisconnectProvider(context.Context, *DisconnectProvider_Request) (*DisconnectProvider_Response, error)
	// DisconnectConnection removes a single connection by id, for providers (like Trello) that can
	// hold more than one connection per user — DisconnectProvider removes the sole connection for a
	// single-connection provider instead.
	DisconnectConnection(context.Context, *DisconnectConnection_Request) (*DisconnectConnection_Response, error)
	GetGooglePickerToken(context.Context, *GooglePickerToken_Request) (*GooglePickerToken_Response, error)
	AddSpreadsheet(context.Context, *AddSpreadsheet_Request) (*AddSpreadsheet_Response, error)
	ListSpreadsheets(context.Context, *ListSpreadsheets_Request) (*ListSpreadsheets_Response, error)
	RemoveSpreadsheet(context.Context, *RemoveSpreadsheet_Request) (*RemoveSpreadsheet_Response, error)
	AddEmailConnection(context.Context, *AddEmailConnection_Request) (*AddEmailConnection_Response, error)
	CheckEmailConnection(context.Context, *CheckEmailConnection_Request) (*CheckEmailConnection_Response, error)
	ListMailServerSuggestions(context.Context, *ListMailServerSuggestions_Request) (*ListMailServerSuggestions_Response, error)
	AddGitlabConnection(context.Context, *AddGitlabConnection_Request) (*AddGitlabConnection_Response, error)
	CheckGitlabConnection(context.Context, *CheckGitlabConnection_Request) (*CheckGitlabConnection_Response, error)
	GenerateGitlabWebhookSecret(context.Context, *GenerateGitlabWebhookSecret_Request) (*GenerateGitlabWebhookSecret_Response, error)
	AddTrelloConnection(context.Context, *AddTrelloConnection_Request) (*AddTrelloConnection_Response, error)
	CheckTrelloConnection(context.Context, *CheckTrelloConnection_Request) (*CheckTrelloConnection_Response, error)
	AddTelegramConnection(context.Context, *AddTelegramConnection_Request) (*AddTelegramConnection_Response, error)
	CheckTelegramConnection(context.Context, *CheckTelegramConnection_Request) (*CheckTelegramConnection_Response, error)
	AddAnthropicConnection(context.Context, *AddAnthropicConnection_Request) (*AddAnthropicConnection_Response, error)
	CheckAnthropicConnection(context.Context, *CheckAnthropicConnection_Request) (*CheckAnthropicConnection_Response, error)
	AddGenericConnection(context.Context, *AddGenericConnection_Request) (*AddGenericConnection_Response, error)
	mustEmbedUnimplementedExternalConnectionsAPIServer()
}

// UnimplementedExternalConnectionsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalConnectionsAPIServer struct{}

func (UnimplementedExternalConnectionsAPIServer) InitiateGoogleOAuth(context.Context, *InitiateGoogleOAuth_Request) (*InitiateGoogleOAuth_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateGoogleOAuth not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) ListConnections(context.Context, *ListConnections_Request) (*ListConnections_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) DisconnectProvider(context.Context, *DisconnectProvider_Request) (*DisconnectProvider_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectProvider not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) DisconnectConnection(context.Context, *DisconnectConnection_Request) (*DisconnectConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) GetGooglePickerToken(context.Context, *GooglePickerToken_Request) (*GooglePickerToken_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGooglePickerToken not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) AddSpreadsheet(context.Context, *AddSpreadsheet_Request) (*AddSpreadsheet_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSpreadsheet not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) ListSpreadsheets(context.Context, *ListSpreadsheets_Request) (*ListSpreadsheets_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSpreadsheets not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) RemoveSpreadsheet(context.Context, *RemoveSpreadsheet_Request) (*RemoveSpreadsheet_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSpreadsheet not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) AddEmailConnection(context.Context, *AddEmailConnection_Request) (*AddEmailConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEmailConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) CheckEmailConnection(context.Context, *CheckEmailConnection_Request) (*CheckEmailConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckEmailConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) ListMailServerSuggestions(context.Context, *ListMailServerSuggestions_Request) (*ListMailServerSuggestions_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMailServerSuggestions not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) AddGitlabConnection(context.Context, *AddGitlabConnection_Request) (*AddGitlabConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGitlabConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) CheckGitlabConnection(context.Context, *CheckGitlabConnection_Request) (*CheckGitlabConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckGitlabConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) GenerateGitlabWebhookSecret(context.Context, *GenerateGitlabWebhookSecret_Request) (*GenerateGitlabWebhookSecret_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateGitlabWebhookSecret not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) AddTrelloConnection(context.Context, *AddTrelloConnection_Request) (*AddTrelloConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTrelloConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) CheckTrelloConnection(context.Context, *CheckTrelloConnection_Request) (*CheckTrelloConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTrelloConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) AddTelegramConnection(context.Context, *AddTelegramConnection_Request) (*AddTelegramConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTelegramConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) CheckTelegramConnection(context.Context, *CheckTelegramConnection_Request) (*CheckTelegramConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTelegramConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) AddAnthropicConnection(context.Context, *AddAnthropicConnection_Request) (*AddAnthropicConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAnthropicConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) CheckAnthropicConnection(context.Context, *CheckAnthropicConnection_Request) (*CheckAnthropicConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAnthropicConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) AddGenericConnection(context.Context, *AddGenericConnection_Request) (*AddGenericConnection_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGenericConnection not implemented")
}
func (UnimplementedExternalConnectionsAPIServer) mustEmbedUnimplementedExternalConnectionsAPIServer() {
}
func (UnimplementedExternalConnectionsAPIServer) testEmbeddedByValue() {}

// UnsafeExternalConnectionsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalConnectionsAPIServer will
// result in compilation errors.
type UnsafeExternalConnectionsAPIServer interface {
	mustEmbedUnimplementedExternalConnectionsAPIServer()
}

func RegisterExternalConnectionsAPIServer(s grpc.ServiceRegistrar, srv ExternalConnectionsAPIServer) {
	// If the following call panics, it indicates UnimplementedExternalConnectionsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalConnectionsAPI_ServiceDesc, srv)
}

func _ExternalConnectionsAPI_InitiateGoogleOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateGoogleOAuth_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).InitiateGoogleOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_InitiateGoogleOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).InitiateGoogleOAuth(ctx, req.(*InitiateGoogleOAuth_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnections_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).ListConnections(ctx, req.(*ListConnections_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_DisconnectProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectProvider_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).DisconnectProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_DisconnectProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).DisconnectProvider(ctx, req.(*DisconnectProvider_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_DisconnectConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).DisconnectConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_DisconnectConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).DisconnectConnection(ctx, req.(*DisconnectConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_GetGooglePickerToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GooglePickerToken_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).GetGooglePickerToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_GetGooglePickerToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).GetGooglePickerToken(ctx, req.(*GooglePickerToken_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_AddSpreadsheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSpreadsheet_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).AddSpreadsheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_AddSpreadsheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).AddSpreadsheet(ctx, req.(*AddSpreadsheet_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_ListSpreadsheets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpreadsheets_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).ListSpreadsheets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_ListSpreadsheets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).ListSpreadsheets(ctx, req.(*ListSpreadsheets_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_RemoveSpreadsheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSpreadsheet_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).RemoveSpreadsheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_RemoveSpreadsheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).RemoveSpreadsheet(ctx, req.(*RemoveSpreadsheet_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_AddEmailConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEmailConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).AddEmailConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_AddEmailConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).AddEmailConnection(ctx, req.(*AddEmailConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_CheckEmailConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEmailConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).CheckEmailConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_CheckEmailConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).CheckEmailConnection(ctx, req.(*CheckEmailConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_ListMailServerSuggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMailServerSuggestions_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).ListMailServerSuggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_ListMailServerSuggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).ListMailServerSuggestions(ctx, req.(*ListMailServerSuggestions_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_AddGitlabConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGitlabConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).AddGitlabConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_AddGitlabConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).AddGitlabConnection(ctx, req.(*AddGitlabConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_CheckGitlabConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckGitlabConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).CheckGitlabConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_CheckGitlabConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).CheckGitlabConnection(ctx, req.(*CheckGitlabConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_GenerateGitlabWebhookSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateGitlabWebhookSecret_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).GenerateGitlabWebhookSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_GenerateGitlabWebhookSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).GenerateGitlabWebhookSecret(ctx, req.(*GenerateGitlabWebhookSecret_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_AddTrelloConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTrelloConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).AddTrelloConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_AddTrelloConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).AddTrelloConnection(ctx, req.(*AddTrelloConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_CheckTrelloConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTrelloConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).CheckTrelloConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_CheckTrelloConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).CheckTrelloConnection(ctx, req.(*CheckTrelloConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_AddTelegramConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTelegramConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).AddTelegramConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_AddTelegramConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).AddTelegramConnection(ctx, req.(*AddTelegramConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_CheckTelegramConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTelegramConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).CheckTelegramConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_CheckTelegramConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).CheckTelegramConnection(ctx, req.(*CheckTelegramConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_AddAnthropicConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAnthropicConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).AddAnthropicConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_AddAnthropicConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).AddAnthropicConnection(ctx, req.(*AddAnthropicConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_CheckAnthropicConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAnthropicConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).CheckAnthropicConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_CheckAnthropicConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).CheckAnthropicConnection(ctx, req.(*CheckAnthropicConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalConnectionsAPI_AddGenericConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGenericConnection_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalConnectionsAPIServer).AddGenericConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalConnectionsAPI_AddGenericConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalConnectionsAPIServer).AddGenericConnection(ctx, req.(*AddGenericConnection_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalConnectionsAPI_ServiceDesc is the grpc.ServiceDesc for ExternalConnectionsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalConnectionsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artel_api.ExternalConnectionsAPI",
	HandlerType: (*ExternalConnectionsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateGoogleOAuth",
			Handler:    _ExternalConnectionsAPI_InitiateGoogleOAuth_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _ExternalConnectionsAPI_ListConnections_Handler,
		},
		{
			MethodName: "DisconnectProvider",
			Handler:    _ExternalConnectionsAPI_DisconnectProvider_Handler,
		},
		{
			MethodName: "DisconnectConnection",
			Handler:    _ExternalConnectionsAPI_DisconnectConnection_Handler,
		},
		{
			MethodName: "GetGooglePickerToken",
			Handler:    _ExternalConnectionsAPI_GetGooglePickerToken_Handler,
		},
		{
			MethodName: "AddSpreadsheet",
			Handler:    _ExternalConnectionsAPI_AddSpreadsheet_Handler,
		},
		{
			MethodName: "ListSpreadsheets",
			Handler:    _ExternalConnectionsAPI_ListSpreadsheets_Handler,
		},
		{
			MethodName: "RemoveSpreadsheet",
			Handler:    _ExternalConnectionsAPI_RemoveSpreadsheet_Handler,
		},
		{
			MethodName: "AddEmailConnection",
			Handler:    _ExternalConnectionsAPI_AddEmailConnection_Handler,
		},
		{
			MethodName: "CheckEmailConnection",
			Handler:    _ExternalConnectionsAPI_CheckEmailConnection_Handler,
		},
		{
			MethodName: "ListMailServerSuggestions",
			Handler:    _ExternalConnectionsAPI_ListMailServerSuggestions_Handler,
		},
		{
			MethodName: "AddGitlabConnection",
			Handler:    _ExternalConnectionsAPI_AddGitlabConnection_Handler,
		},
		{
			MethodName: "CheckGitlabConnection",
			Handler:    _ExternalConnectionsAPI_CheckGitlabConnection_Handler,
		},
		{
			MethodName: "GenerateGitlabWebhookSecret",
			Handler:    _ExternalConnectionsAPI_GenerateGitlabWebhookSecret_Handler,
		},
		{
			MethodName: "AddTrelloConnection",
			Handler:    _ExternalConnectionsAPI_AddTrelloConnection_Handler,
		},
		{
			MethodName: "CheckTrelloConnection",
			Handler:    _ExternalConnectionsAPI_CheckTrelloConnection_Handler,
		},
		{
			MethodName: "AddTelegramConnection",
			Handler:    _ExternalConnectionsAPI_AddTelegramConnection_Handler,
		},
		{
			MethodName: "CheckTelegramConnection",
			Handler:    _ExternalConnectionsAPI_CheckTelegramConnection_Handler,
		},
		{
			MethodName: "AddAnthropicConnection",
			Handler:    _ExternalConnectionsAPI_AddAnthropicConnection_Handler,
		},
		{
			MethodName: "CheckAnthropicConnection",
			Handler:    _ExternalConnectionsAPI_CheckAnthropicConnection_Handler,
		},
		{
			MethodName: "AddGenericConnection",
			Handler:    _ExternalConnectionsAPI_AddGenericConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "external_connections.proto",
}
