// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: mcp_keys.proto

package artel_api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	McpKeysAPI_CreateMcpKey_FullMethodName             = "/artel_api.McpKeysAPI/CreateMcpKey"
	McpKeysAPI_ListMcpKeys_FullMethodName              = "/artel_api.McpKeysAPI/ListMcpKeys"
	McpKeysAPI_RevokeMcpKey_FullMethodName             = "/artel_api.McpKeysAPI/RevokeMcpKey"
	McpKeysAPI_ListUserMcpKeys_FullMethodName          = "/artel_api.McpKeysAPI/ListUserMcpKeys"
	McpKeysAPI_SetMcpKeyAccess_FullMethodName          = "/artel_api.McpKeysAPI/SetMcpKeyAccess"
	McpKeysAPI_ListMcpConnectors_FullMethodName        = "/artel_api.McpKeysAPI/ListMcpConnectors"
	McpKeysAPI_AddMcpConnector_FullMethodName          = "/artel_api.McpKeysAPI/AddMcpConnector"
	McpKeysAPI_RemoveMcpConnector_FullMethodName       = "/artel_api.McpKeysAPI/RemoveMcpConnector"
	McpKeysAPI_ListMomCandidates_FullMethodName        = "/artel_api.McpKeysAPI/ListMomCandidates"
	McpKeysAPI_ListCommunityConnectors_FullMethodName  = "/artel_api.McpKeysAPI/ListCommunityConnectors"
	McpKeysAPI_DeleteCommunityConnector_FullMethodName = "/artel_api.McpKeysAPI/DeleteCommunityConnector"
	McpKeysAPI_ExecuteMomTool_FullMethodName           = "/artel_api.McpKeysAPI/ExecuteMomTool"
)

// McpKeysAPIClient is the client API for McpKeysAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpKeysAPIClient interface {
	CreateMcpKey(ctx context.Context, in *CreateMcpKey_Request, opts ...grpc.CallOption) (*CreateMcpKey_Response, error)
	ListMcpKeys(ctx context.Context, in *ListMcpKeys_Request, opts ...grpc.CallOption) (*ListMcpKeys_Response, error)
	RevokeMcpKey(ctx context.Context, in *RevokeMcpKey_Request, opts ...grpc.CallOption) (*RevokeMcpKey_Response, error)
	ListUserMcpKeys(ctx context.Context, in *ListUserMcpKeys_Request, opts ...grpc.CallOption) (*ListUserMcpKeys_Response, error)
	SetMcpKeyAccess(ctx context.Context, in *SetMcpKeyAccess_Request, opts ...grpc.CallOption) (*SetMcpKeyAccess_Response, error)
	ListMcpConnectors(ctx context.Context, in *ListMcpConnectors_Request, opts ...grpc.CallOption) (*ListMcpConnectors_Response, error)
	AddMcpConnector(ctx context.Context, in *AddMcpConnector_Request, opts ...grpc.CallOption) (*AddMcpConnector_Response, error)
	RemoveMcpConnector(ctx context.Context, in *RemoveMcpConnector_Request, opts ...grpc.CallOption) (*RemoveMcpConnector_Response, error)
	ListMomCandidates(ctx context.Context, in *ListMomCandidates_Request, opts ...grpc.CallOption) (*ListMomCandidates_Response, error)
	ListCommunityConnectors(ctx context.Context, in *ListCommunityConnectors_Request, opts ...grpc.CallOption) (*ListCommunityConnectors_Response, error)
	DeleteCommunityConnector(ctx context.Context, in *DeleteCommunityConnector_Request, opts ...grpc.CallOption) (*DeleteCommunityConnector_Response, error)
	ExecuteMomTool(ctx context.Context, in *ExecuteMomTool_Request, opts ...grpc.CallOption) (*ExecuteMomTool_Response, error)
}

type mcpKeysAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpKeysAPIClient(cc grpc.ClientConnInterface) McpKeysAPIClient {
	return &mcpKeysAPIClient{cc}
}

func (c *mcpKeysAPIClient) CreateMcpKey(ctx context.Context, in *CreateMcpKey_Request, opts ...grpc.CallOption) (*CreateMcpKey_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMcpKey_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_CreateMcpKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) ListMcpKeys(ctx context.Context, in *ListMcpKeys_Request, opts ...grpc.CallOption) (*ListMcpKeys_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMcpKeys_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_ListMcpKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) RevokeMcpKey(ctx context.Context, in *RevokeMcpKey_Request, opts ...grpc.CallOption) (*RevokeMcpKey_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeMcpKey_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_RevokeMcpKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) ListUserMcpKeys(ctx context.Context, in *ListUserMcpKeys_Request, opts ...grpc.CallOption) (*ListUserMcpKeys_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserMcpKeys_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_ListUserMcpKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) SetMcpKeyAccess(ctx context.Context, in *SetMcpKeyAccess_Request, opts ...grpc.CallOption) (*SetMcpKeyAccess_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMcpKeyAccess_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_SetMcpKeyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) ListMcpConnectors(ctx context.Context, in *ListMcpConnectors_Request, opts ...grpc.CallOption) (*ListMcpConnectors_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMcpConnectors_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_ListMcpConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) AddMcpConnector(ctx context.Context, in *AddMcpConnector_Request, opts ...grpc.CallOption) (*AddMcpConnector_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMcpConnector_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_AddMcpConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) RemoveMcpConnector(ctx context.Context, in *RemoveMcpConnector_Request, opts ...grpc.CallOption) (*RemoveMcpConnector_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMcpConnector_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_RemoveMcpConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) ListMomCandidates(ctx context.Context, in *ListMomCandidates_Request, opts ...grpc.CallOption) (*ListMomCandidates_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMomCandidates_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_ListMomCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) ListCommunityConnectors(ctx context.Context, in *ListCommunityConnectors_Request, opts ...grpc.CallOption) (*ListCommunityConnectors_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommunityConnectors_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_ListCommunityConnectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) DeleteCommunityConnector(ctx context.Context, in *DeleteCommunityConnector_Request, opts ...grpc.CallOption) (*DeleteCommunityConnector_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCommunityConnector_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_DeleteCommunityConnector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) ExecuteMomTool(ctx context.Context, in *ExecuteMomTool_Request, opts ...grpc.CallOption) (*ExecuteMomTool_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteMomTool_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_ExecuteMomTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpKeysAPIServer is the server API for McpKeysAPI service.
// All implementations must embed UnimplementedMcpKeysAPIServer
// for forward compatibility.
type McpKeysAPIServer interface {
	CreateMcpKey(context.Context, *CreateMcpKey_Request) (*CreateMcpKey_Response, error)
	ListMcpKeys(context.Context, *ListMcpKeys_Request) (*ListMcpKeys_Response, error)
	RevokeMcpKey(context.Context, *RevokeMcpKey_Request) (*RevokeMcpKey_Response, error)
	ListUserMcpKeys(context.Context, *ListUserMcpKeys_Request) (*ListUserMcpKeys_Response, error)
	SetMcpKeyAccess(context.Context, *SetMcpKeyAccess_Request) (*SetMcpKeyAccess_Response, error)
	ListMcpConnectors(context.Context, *ListMcpConnectors_Request) (*ListMcpConnectors_Response, error)
	AddMcpConnector(context.Context, *AddMcpConnector_Request) (*AddMcpConnector_Response, error)
	RemoveMcpConnector(context.Context, *RemoveMcpConnector_Request) (*RemoveMcpConnector_Response, error)
	ListMomCandidates(context.Context, *ListMomCandidates_Request) (*ListMomCandidates_Response, error)
	ListCommunityConnectors(context.Context, *ListCommunityConnectors_Request) (*ListCommunityConnectors_Response, error)
	DeleteCommunityConnector(context.Context, *DeleteCommunityConnector_Request) (*DeleteCommunityConnector_Response, error)
	ExecuteMomTool(context.Context, *ExecuteMomTool_Request) (*ExecuteMomTool_Response, error)
	mustEmbedUnimplementedMcpKeysAPIServer()
}

// UnimplementedMcpKeysAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMcpKeysAPIServer struct{}

func (UnimplementedMcpKeysAPIServer) CreateMcpKey(context.Context, *CreateMcpKey_Request) (*CreateMcpKey_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMcpKey not implemented")
}
func (UnimplementedMcpKeysAPIServer) ListMcpKeys(context.Context, *ListMcpKeys_Request) (*ListMcpKeys_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcpKeys not implemented")
}
func (UnimplementedMcpKeysAPIServer) RevokeMcpKey(context.Context, *RevokeMcpKey_Request) (*RevokeMcpKey_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeMcpKey not implemented")
}
func (UnimplementedMcpKeysAPIServer) ListUserMcpKeys(context.Context, *ListUserMcpKeys_Request) (*ListUserMcpKeys_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserMcpKeys not implemented")
}
func (UnimplementedMcpKeysAPIServer) SetMcpKeyAccess(context.Context, *SetMcpKeyAccess_Request) (*SetMcpKeyAccess_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMcpKeyAccess not implemented")
}
func (UnimplementedMcpKeysAPIServer) ListMcpConnectors(context.Context, *ListMcpConnectors_Request) (*ListMcpConnectors_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMcpConnectors not implemented")
}
func (UnimplementedMcpKeysAPIServer) AddMcpConnector(context.Context, *AddMcpConnector_Request) (*AddMcpConnector_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMcpConnector not implemented")
}
func (UnimplementedMcpKeysAPIServer) RemoveMcpConnector(context.Context, *RemoveMcpConnector_Request) (*RemoveMcpConnector_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMcpConnector not implemented")
}
func (UnimplementedMcpKeysAPIServer) ListMomCandidates(context.Context, *ListMomCandidates_Request) (*ListMomCandidates_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMomCandidates not implemented")
}
func (UnimplementedMcpKeysAPIServer) ListCommunityConnectors(context.Context, *ListCommunityConnectors_Request) (*ListCommunityConnectors_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommunityConnectors not implemented")
}
func (UnimplementedMcpKeysAPIServer) DeleteCommunityConnector(context.Context, *DeleteCommunityConnector_Request) (*DeleteCommunityConnector_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCommunityConnector not implemented")
}
func (UnimplementedMcpKeysAPIServer) ExecuteMomTool(context.Context, *ExecuteMomTool_Request) (*ExecuteMomTool_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteMomTool not implemented")
}
func (UnimplementedMcpKeysAPIServer) mustEmbedUnimplementedMcpKeysAPIServer() {}
func (UnimplementedMcpKeysAPIServer) testEmbeddedByValue()                    {}

// UnsafeMcpKeysAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpKeysAPIServer will
// result in compilation errors.
type UnsafeMcpKeysAPIServer interface {
	mustEmbedUnimplementedMcpKeysAPIServer()
}

func RegisterMcpKeysAPIServer(s grpc.ServiceRegistrar, srv McpKeysAPIServer) {
	// If the following call panics, it indicates UnimplementedMcpKeysAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&McpKeysAPI_ServiceDesc, srv)
}

func _McpKeysAPI_CreateMcpKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMcpKey_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).CreateMcpKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_CreateMcpKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).CreateMcpKey(ctx, req.(*CreateMcpKey_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_ListMcpKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpKeys_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).ListMcpKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_ListMcpKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).ListMcpKeys(ctx, req.(*ListMcpKeys_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_RevokeMcpKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMcpKey_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).RevokeMcpKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_RevokeMcpKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).RevokeMcpKey(ctx, req.(*RevokeMcpKey_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_ListUserMcpKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserMcpKeys_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).ListUserMcpKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_ListUserMcpKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).ListUserMcpKeys(ctx, req.(*ListUserMcpKeys_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_SetMcpKeyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMcpKeyAccess_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).SetMcpKeyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_SetMcpKeyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).SetMcpKeyAccess(ctx, req.(*SetMcpKeyAccess_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_ListMcpConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpConnectors_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).ListMcpConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_ListMcpConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).ListMcpConnectors(ctx, req.(*ListMcpConnectors_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_AddMcpConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMcpConnector_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).AddMcpConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_AddMcpConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).AddMcpConnector(ctx, req.(*AddMcpConnector_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_RemoveMcpConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMcpConnector_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).RemoveMcpConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_RemoveMcpConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).RemoveMcpConnector(ctx, req.(*RemoveMcpConnector_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_ListMomCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMomCandidates_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).ListMomCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_ListMomCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).ListMomCandidates(ctx, req.(*ListMomCandidates_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_ListCommunityConnectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommunityConnectors_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).ListCommunityConnectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_ListCommunityConnectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).ListCommunityConnectors(ctx, req.(*ListCommunityConnectors_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_DeleteCommunityConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommunityConnector_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).DeleteCommunityConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_DeleteCommunityConnector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).DeleteCommunityConnector(ctx, req.(*DeleteCommunityConnector_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_ExecuteMomTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteMomTool_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).ExecuteMomTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_ExecuteMomTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).ExecuteMomTool(ctx, req.(*ExecuteMomTool_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// McpKeysAPI_ServiceDesc is the grpc.ServiceDesc for McpKeysAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var McpKeysAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artel_api.McpKeysAPI",
	HandlerType: (*McpKeysAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMcpKey",
			Handler:    _McpKeysAPI_CreateMcpKey_Handler,
		},
		{
			MethodName: "ListMcpKeys",
			Handler:    _McpKeysAPI_ListMcpKeys_Handler,
		},
		{
			MethodName: "RevokeMcpKey",
			Handler:    _McpKeysAPI_RevokeMcpKey_Handler,
		},
		{
			MethodName: "ListUserMcpKeys",
			Handler:    _McpKeysAPI_ListUserMcpKeys_Handler,
		},
		{
			MethodName: "SetMcpKeyAccess",
			Handler:    _McpKeysAPI_SetMcpKeyAccess_Handler,
		},
		{
			MethodName: "ListMcpConnectors",
			Handler:    _McpKeysAPI_ListMcpConnectors_Handler,
		},
		{
			MethodName: "AddMcpConnector",
			Handler:    _McpKeysAPI_AddMcpConnector_Handler,
		},
		{
			MethodName: "RemoveMcpConnector",
			Handler:    _McpKeysAPI_RemoveMcpConnector_Handler,
		},
		{
			MethodName: "ListMomCandidates",
			Handler:    _McpKeysAPI_ListMomCandidates_Handler,
		},
		{
			MethodName: "ListCommunityConnectors",
			Handler:    _McpKeysAPI_ListCommunityConnectors_Handler,
		},
		{
			MethodName: "DeleteCommunityConnector",
			Handler:    _McpKeysAPI_DeleteCommunityConnector_Handler,
		},
		{
			MethodName: "ExecuteMomTool",
			Handler:    _McpKeysAPI_ExecuteMomTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcp_keys.proto",
}
