// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: mcp_keys.proto

package artel_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	McpKeysAPI_CreateMcpKey_FullMethodName = "/artel_api.McpKeysAPI/CreateMcpKey"
	McpKeysAPI_ListMcpKeys_FullMethodName  = "/artel_api.McpKeysAPI/ListMcpKeys"
	McpKeysAPI_RevokeMcpKey_FullMethodName = "/artel_api.McpKeysAPI/RevokeMcpKey"
)

// McpKeysAPIClient is the client API for McpKeysAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpKeysAPIClient interface {
	CreateMcpKey(ctx context.Context, in *CreateMcpKey_Request, opts ...grpc.CallOption) (*CreateMcpKey_Response, error)
	ListMcpKeys(ctx context.Context, in *ListMcpKeys_Request, opts ...grpc.CallOption) (*ListMcpKeys_Response, error)
	RevokeMcpKey(ctx context.Context, in *RevokeMcpKey_Request, opts ...grpc.CallOption) (*RevokeMcpKey_Response, error)
}

type mcpKeysAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpKeysAPIClient(cc grpc.ClientConnInterface) McpKeysAPIClient {
	return &mcpKeysAPIClient{cc}
}

func (c *mcpKeysAPIClient) CreateMcpKey(ctx context.Context, in *CreateMcpKey_Request, opts ...grpc.CallOption) (*CreateMcpKey_Response, error) {
	out := new(CreateMcpKey_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_CreateMcpKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) ListMcpKeys(ctx context.Context, in *ListMcpKeys_Request, opts ...grpc.CallOption) (*ListMcpKeys_Response, error) {
	out := new(ListMcpKeys_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_ListMcpKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpKeysAPIClient) RevokeMcpKey(ctx context.Context, in *RevokeMcpKey_Request, opts ...grpc.CallOption) (*RevokeMcpKey_Response, error) {
	out := new(RevokeMcpKey_Response)
	err := c.cc.Invoke(ctx, McpKeysAPI_RevokeMcpKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpKeysAPIServer is the server API for McpKeysAPI service.
// All implementations must embed UnimplementedMcpKeysAPIServer
// for forward compatibility
type McpKeysAPIServer interface {
	CreateMcpKey(context.Context, *CreateMcpKey_Request) (*CreateMcpKey_Response, error)
	ListMcpKeys(context.Context, *ListMcpKeys_Request) (*ListMcpKeys_Response, error)
	RevokeMcpKey(context.Context, *RevokeMcpKey_Request) (*RevokeMcpKey_Response, error)
	mustEmbedUnimplementedMcpKeysAPIServer()
}

// UnimplementedMcpKeysAPIServer must be embedded to have forward compatible implementations.
type UnimplementedMcpKeysAPIServer struct {
}

func (UnimplementedMcpKeysAPIServer) CreateMcpKey(context.Context, *CreateMcpKey_Request) (*CreateMcpKey_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMcpKey not implemented")
}
func (UnimplementedMcpKeysAPIServer) ListMcpKeys(context.Context, *ListMcpKeys_Request) (*ListMcpKeys_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMcpKeys not implemented")
}
func (UnimplementedMcpKeysAPIServer) RevokeMcpKey(context.Context, *RevokeMcpKey_Request) (*RevokeMcpKey_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeMcpKey not implemented")
}
func (UnimplementedMcpKeysAPIServer) mustEmbedUnimplementedMcpKeysAPIServer() {}

// UnsafeMcpKeysAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpKeysAPIServer will
// result in compilation errors.
type UnsafeMcpKeysAPIServer interface {
	mustEmbedUnimplementedMcpKeysAPIServer()
}

func RegisterMcpKeysAPIServer(s grpc.ServiceRegistrar, srv McpKeysAPIServer) {
	s.RegisterService(&McpKeysAPI_ServiceDesc, srv)
}

func _McpKeysAPI_CreateMcpKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMcpKey_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).CreateMcpKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_CreateMcpKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).CreateMcpKey(ctx, req.(*CreateMcpKey_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_ListMcpKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMcpKeys_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).ListMcpKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_ListMcpKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).ListMcpKeys(ctx, req.(*ListMcpKeys_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _McpKeysAPI_RevokeMcpKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMcpKey_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpKeysAPIServer).RevokeMcpKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: McpKeysAPI_RevokeMcpKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpKeysAPIServer).RevokeMcpKey(ctx, req.(*RevokeMcpKey_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// McpKeysAPI_ServiceDesc is the grpc.ServiceDesc for McpKeysAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var McpKeysAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artel_api.McpKeysAPI",
	HandlerType: (*McpKeysAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMcpKey",
			Handler:    _McpKeysAPI_CreateMcpKey_Handler,
		},
		{
			MethodName: "ListMcpKeys",
			Handler:    _McpKeysAPI_ListMcpKeys_Handler,
		},
		{
			MethodName: "RevokeMcpKey",
			Handler:    _McpKeysAPI_RevokeMcpKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcp_keys.proto",
}
