// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: notes.proto

package artel_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mtime         int64                  `protobuf:"varint,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteItem) Reset() {
	*x = NoteItem{}
	mi := &file_notes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteItem) ProtoMessage() {}

func (x *NoteItem) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteItem.ProtoReflect.Descriptor instead.
func (*NoteItem) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{0}
}

func (x *NoteItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NoteItem) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type ListFolders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFolders) Reset() {
	*x = ListFolders{}
	mi := &file_notes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFolders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFolders) ProtoMessage() {}

func (x *ListFolders) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFolders.ProtoReflect.Descriptor instead.
func (*ListFolders) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1}
}

type ListNotes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotes) Reset() {
	*x = ListNotes{}
	mi := &file_notes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotes) ProtoMessage() {}

func (x *ListNotes) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotes.ProtoReflect.Descriptor instead.
func (*ListNotes) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{2}
}

type GetNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNote) Reset() {
	*x = GetNote{}
	mi := &file_notes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNote) ProtoMessage() {}

func (x *GetNote) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNote.ProtoReflect.Descriptor instead.
func (*GetNote) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{3}
}

type ListTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTags) Reset() {
	*x = ListTags{}
	mi := &file_notes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTags) ProtoMessage() {}

func (x *ListTags) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTags.ProtoReflect.Descriptor instead.
func (*ListTags) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{4}
}

type SaveNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNote) Reset() {
	*x = SaveNote{}
	mi := &file_notes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNote) ProtoMessage() {}

func (x *SaveNote) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNote.ProtoReflect.Descriptor instead.
func (*SaveNote) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{5}
}

type ListFolders_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFolders_Request) Reset() {
	*x = ListFolders_Request{}
	mi := &file_notes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFolders_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFolders_Request) ProtoMessage() {}

func (x *ListFolders_Request) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFolders_Request.ProtoReflect.Descriptor instead.
func (*ListFolders_Request) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListFolders_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type ListFolders_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []string               `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFolders_Response) Reset() {
	*x = ListFolders_Response{}
	mi := &file_notes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFolders_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFolders_Response) ProtoMessage() {}

func (x *ListFolders_Response) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFolders_Response.ProtoReflect.Descriptor instead.
func (*ListFolders_Response) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListFolders_Response) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

type ListNotes_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotes_Request) Reset() {
	*x = ListNotes_Request{}
	mi := &file_notes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotes_Request) ProtoMessage() {}

func (x *ListNotes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotes_Request.ProtoReflect.Descriptor instead.
func (*ListNotes_Request) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListNotes_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type ListNotes_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*NoteItem            `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotes_Response) Reset() {
	*x = ListNotes_Response{}
	mi := &file_notes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotes_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotes_Response) ProtoMessage() {}

func (x *ListNotes_Response) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotes_Response.ProtoReflect.Descriptor instead.
func (*ListNotes_Response) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ListNotes_Response) GetNotes() []*NoteItem {
	if x != nil {
		return x.Notes
	}
	return nil
}

type GetNote_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNote_Request) Reset() {
	*x = GetNote_Request{}
	mi := &file_notes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNote_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNote_Request) ProtoMessage() {}

func (x *GetNote_Request) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNote_Request.ProtoReflect.Descriptor instead.
func (*GetNote_Request) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetNote_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *GetNote_Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetNote_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNote_Response) Reset() {
	*x = GetNote_Response{}
	mi := &file_notes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNote_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNote_Response) ProtoMessage() {}

func (x *GetNote_Response) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNote_Response.ProtoReflect.Descriptor instead.
func (*GetNote_Response) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetNote_Response) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ListTags_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTags_Request) Reset() {
	*x = ListTags_Request{}
	mi := &file_notes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTags_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTags_Request) ProtoMessage() {}

func (x *ListTags_Request) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTags_Request.ProtoReflect.Descriptor instead.
func (*ListTags_Request) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ListTags_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type ListTags_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTags_Response) Reset() {
	*x = ListTags_Response{}
	mi := &file_notes_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTags_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTags_Response) ProtoMessage() {}

func (x *ListTags_Response) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTags_Response.ProtoReflect.Descriptor instead.
func (*ListTags_Response) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ListTags_Response) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SaveNote_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNote_Request) Reset() {
	*x = SaveNote_Request{}
	mi := &file_notes_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNote_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNote_Request) ProtoMessage() {}

func (x *SaveNote_Request) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNote_Request.ProtoReflect.Descriptor instead.
func (*SaveNote_Request) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{5, 0}
}

func (x *SaveNote_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *SaveNote_Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SaveNote_Request) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SaveNote_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveNote_Response) Reset() {
	*x = SaveNote_Response{}
	mi := &file_notes_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveNote_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveNote_Response) ProtoMessage() {}

func (x *SaveNote_Response) ProtoReflect() protoreflect.Message {
	mi := &file_notes_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveNote_Response.ProtoReflect.Descriptor instead.
func (*SaveNote_Response) Descriptor() ([]byte, []int) {
	return file_notes_proto_rawDescGZIP(), []int{5, 1}
}

var File_notes_proto protoreflect.FileDescriptor

const file_notes_proto_rawDesc = "" +
	"\n" +
	"\vnotes.proto\x12\vartel_notes\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\"4\n" +
	"\bNoteItem\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05mtime\x18\x02 \x01(\x03R\x05mtime\"Y\n" +
	"\vListFolders\x1a$\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\afolders\x18\x01 \x03(\tR\afolders\"j\n" +
	"\tListNotes\x1a$\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x1a7\n" +
	"\bResponse\x12+\n" +
	"\x05notes\x18\x01 \x03(\v2\x15.artel_notes.NoteItemR\x05notes\"i\n" +
	"\aGetNote\x1a8\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"P\n" +
	"\bListTags\x1a$\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"j\n" +
	"\bSaveNote\x1aR\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x1a\n" +
	"\n" +
	"\bResponse2\x98\x04\n" +
	"\bNotesAPI\x12q\n" +
	"\vListFolders\x12 .artel_notes.ListFolders.Request\x1a!.artel_notes.ListFolders.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/notes/folders\x12h\n" +
	"\tListNotes\x12\x1e.artel_notes.ListNotes.Request\x1a\x1f.artel_notes.ListNotes.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/notes/list\x12a\n" +
	"\aGetNote\x12\x1c.artel_notes.GetNote.Request\x1a\x1d.artel_notes.GetNote.Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/notes/get\x12e\n" +
	"\bListTags\x12\x1d.artel_notes.ListTags.Request\x1a\x1e.artel_notes.ListTags.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/notes/tags\x12e\n" +
	"\bSaveNote\x12\x1d.artel_notes.SaveNote.Request\x1a\x1e.artel_notes.SaveNote.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/notes/saveB\x1a\x92\x82\x19\n" +
	"@artel/apiZ\n" +
	"/artel_apib\x06proto3"

var (
	file_notes_proto_rawDescOnce sync.Once
	file_notes_proto_rawDescData []byte
)

func file_notes_proto_rawDescGZIP() []byte {
	file_notes_proto_rawDescOnce.Do(func() {
		file_notes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notes_proto_rawDesc), len(file_notes_proto_rawDesc)))
	})
	return file_notes_proto_rawDescData
}

var file_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_notes_proto_goTypes = []any{
	(*NoteItem)(nil),             // 0: artel_notes.NoteItem
	(*ListFolders)(nil),          // 1: artel_notes.ListFolders
	(*ListNotes)(nil),            // 2: artel_notes.ListNotes
	(*GetNote)(nil),              // 3: artel_notes.GetNote
	(*ListTags)(nil),             // 4: artel_notes.ListTags
	(*SaveNote)(nil),             // 5: artel_notes.SaveNote
	(*ListFolders_Request)(nil),  // 6: artel_notes.ListFolders.Request
	(*ListFolders_Response)(nil), // 7: artel_notes.ListFolders.Response
	(*ListNotes_Request)(nil),    // 8: artel_notes.ListNotes.Request
	(*ListNotes_Response)(nil),   // 9: artel_notes.ListNotes.Response
	(*GetNote_Request)(nil),      // 10: artel_notes.GetNote.Request
	(*GetNote_Response)(nil),     // 11: artel_notes.GetNote.Response
	(*ListTags_Request)(nil),     // 12: artel_notes.ListTags.Request
	(*ListTags_Response)(nil),    // 13: artel_notes.ListTags.Response
	(*SaveNote_Request)(nil),     // 14: artel_notes.SaveNote.Request
	(*SaveNote_Response)(nil),    // 15: artel_notes.SaveNote.Response
}
var file_notes_proto_depIdxs = []int32{
	0,  // 0: artel_notes.ListNotes.Response.notes:type_name -> artel_notes.NoteItem
	6,  // 1: artel_notes.NotesAPI.ListFolders:input_type -> artel_notes.ListFolders.Request
	8,  // 2: artel_notes.NotesAPI.ListNotes:input_type -> artel_notes.ListNotes.Request
	10, // 3: artel_notes.NotesAPI.GetNote:input_type -> artel_notes.GetNote.Request
	12, // 4: artel_notes.NotesAPI.ListTags:input_type -> artel_notes.ListTags.Request
	14, // 5: artel_notes.NotesAPI.SaveNote:input_type -> artel_notes.SaveNote.Request
	7,  // 6: artel_notes.NotesAPI.ListFolders:output_type -> artel_notes.ListFolders.Response
	9,  // 7: artel_notes.NotesAPI.ListNotes:output_type -> artel_notes.ListNotes.Response
	11, // 8: artel_notes.NotesAPI.GetNote:output_type -> artel_notes.GetNote.Response
	13, // 9: artel_notes.NotesAPI.ListTags:output_type -> artel_notes.ListTags.Response
	15, // 10: artel_notes.NotesAPI.SaveNote:output_type -> artel_notes.SaveNote.Response
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_notes_proto_init() }
func file_notes_proto_init() {
	if File_notes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notes_proto_rawDesc), len(file_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notes_proto_goTypes,
		DependencyIndexes: file_notes_proto_depIdxs,
		MessageInfos:      file_notes_proto_msgTypes,
	}.Build()
	File_notes_proto = out.File
	file_notes_proto_goTypes = nil
	file_notes_proto_depIdxs = nil
}
