// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: public_docs.proto

package artel_api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVaultBySlug struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVaultBySlug) Reset() {
	*x = GetVaultBySlug{}
	mi := &file_public_docs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVaultBySlug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVaultBySlug) ProtoMessage() {}

func (x *GetVaultBySlug) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVaultBySlug.ProtoReflect.Descriptor instead.
func (*GetVaultBySlug) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{0}
}

type PublicDocsNoteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mtime         int64                  `protobuf:"varint,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsNoteItem) Reset() {
	*x = PublicDocsNoteItem{}
	mi := &file_public_docs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsNoteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsNoteItem) ProtoMessage() {}

func (x *PublicDocsNoteItem) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsNoteItem.ProtoReflect.Descriptor instead.
func (*PublicDocsNoteItem) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{1}
}

func (x *PublicDocsNoteItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PublicDocsNoteItem) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type PublicDocsListFolders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListFolders) Reset() {
	*x = PublicDocsListFolders{}
	mi := &file_public_docs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListFolders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListFolders) ProtoMessage() {}

func (x *PublicDocsListFolders) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListFolders.ProtoReflect.Descriptor instead.
func (*PublicDocsListFolders) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{2}
}

type PublicDocsListNotes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListNotes) Reset() {
	*x = PublicDocsListNotes{}
	mi := &file_public_docs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListNotes) ProtoMessage() {}

func (x *PublicDocsListNotes) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListNotes.ProtoReflect.Descriptor instead.
func (*PublicDocsListNotes) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{3}
}

type PublicDocsGetNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsGetNote) Reset() {
	*x = PublicDocsGetNote{}
	mi := &file_public_docs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsGetNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsGetNote) ProtoMessage() {}

func (x *PublicDocsGetNote) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsGetNote.ProtoReflect.Descriptor instead.
func (*PublicDocsGetNote) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{4}
}

type PublicDocsListTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListTags) Reset() {
	*x = PublicDocsListTags{}
	mi := &file_public_docs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListTags) ProtoMessage() {}

func (x *PublicDocsListTags) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListTags.ProtoReflect.Descriptor instead.
func (*PublicDocsListTags) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{5}
}

type GetVaultBySlug_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVaultBySlug_Request) Reset() {
	*x = GetVaultBySlug_Request{}
	mi := &file_public_docs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVaultBySlug_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVaultBySlug_Request) ProtoMessage() {}

func (x *GetVaultBySlug_Request) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVaultBySlug_Request.ProtoReflect.Descriptor instead.
func (*GetVaultBySlug_Request) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetVaultBySlug_Request) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetVaultBySlug_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVaultBySlug_Response) Reset() {
	*x = GetVaultBySlug_Response{}
	mi := &file_public_docs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVaultBySlug_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVaultBySlug_Response) ProtoMessage() {}

func (x *GetVaultBySlug_Response) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVaultBySlug_Response.ProtoReflect.Descriptor instead.
func (*GetVaultBySlug_Response) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetVaultBySlug_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVaultBySlug_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PublicDocsListFolders_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListFolders_Request) Reset() {
	*x = PublicDocsListFolders_Request{}
	mi := &file_public_docs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListFolders_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListFolders_Request) ProtoMessage() {}

func (x *PublicDocsListFolders_Request) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListFolders_Request.ProtoReflect.Descriptor instead.
func (*PublicDocsListFolders_Request) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{2, 0}
}

func (x *PublicDocsListFolders_Request) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type PublicDocsListFolders_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []string               `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListFolders_Response) Reset() {
	*x = PublicDocsListFolders_Response{}
	mi := &file_public_docs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListFolders_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListFolders_Response) ProtoMessage() {}

func (x *PublicDocsListFolders_Response) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListFolders_Response.ProtoReflect.Descriptor instead.
func (*PublicDocsListFolders_Response) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{2, 1}
}

func (x *PublicDocsListFolders_Response) GetFolders() []string {
	if x != nil {
		return x.Folders
	}
	return nil
}

type PublicDocsListNotes_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListNotes_Request) Reset() {
	*x = PublicDocsListNotes_Request{}
	mi := &file_public_docs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListNotes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListNotes_Request) ProtoMessage() {}

func (x *PublicDocsListNotes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListNotes_Request.ProtoReflect.Descriptor instead.
func (*PublicDocsListNotes_Request) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{3, 0}
}

func (x *PublicDocsListNotes_Request) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type PublicDocsListNotes_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*PublicDocsNoteItem  `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListNotes_Response) Reset() {
	*x = PublicDocsListNotes_Response{}
	mi := &file_public_docs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListNotes_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListNotes_Response) ProtoMessage() {}

func (x *PublicDocsListNotes_Response) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListNotes_Response.ProtoReflect.Descriptor instead.
func (*PublicDocsListNotes_Response) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{3, 1}
}

func (x *PublicDocsListNotes_Response) GetNotes() []*PublicDocsNoteItem {
	if x != nil {
		return x.Notes
	}
	return nil
}

type PublicDocsGetNote_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsGetNote_Request) Reset() {
	*x = PublicDocsGetNote_Request{}
	mi := &file_public_docs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsGetNote_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsGetNote_Request) ProtoMessage() {}

func (x *PublicDocsGetNote_Request) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsGetNote_Request.ProtoReflect.Descriptor instead.
func (*PublicDocsGetNote_Request) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PublicDocsGetNote_Request) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *PublicDocsGetNote_Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PublicDocsGetNote_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsGetNote_Response) Reset() {
	*x = PublicDocsGetNote_Response{}
	mi := &file_public_docs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsGetNote_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsGetNote_Response) ProtoMessage() {}

func (x *PublicDocsGetNote_Response) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsGetNote_Response.ProtoReflect.Descriptor instead.
func (*PublicDocsGetNote_Response) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{4, 1}
}

func (x *PublicDocsGetNote_Response) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PublicDocsListTags_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListTags_Request) Reset() {
	*x = PublicDocsListTags_Request{}
	mi := &file_public_docs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListTags_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListTags_Request) ProtoMessage() {}

func (x *PublicDocsListTags_Request) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListTags_Request.ProtoReflect.Descriptor instead.
func (*PublicDocsListTags_Request) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{5, 0}
}

func (x *PublicDocsListTags_Request) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type PublicDocsListTags_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicDocsListTags_Response) Reset() {
	*x = PublicDocsListTags_Response{}
	mi := &file_public_docs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDocsListTags_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDocsListTags_Response) ProtoMessage() {}

func (x *PublicDocsListTags_Response) ProtoReflect() protoreflect.Message {
	mi := &file_public_docs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDocsListTags_Response.ProtoReflect.Descriptor instead.
func (*PublicDocsListTags_Response) Descriptor() ([]byte, []int) {
	return file_public_docs_proto_rawDescGZIP(), []int{5, 1}
}

func (x *PublicDocsListTags_Response) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_public_docs_proto protoreflect.FileDescriptor

const file_public_docs_proto_rawDesc = "" +
	"\n" +
	"\x11public_docs.proto\x12\x11artel_public_docs\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\"_\n" +
	"\x0eGetVaultBySlug\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x1a.\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\">\n" +
	"\x12PublicDocsNoteItem\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05mtime\x18\x02 \x01(\x03R\x05mtime\"\\\n" +
	"\x15PublicDocsListFolders\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\afolders\x18\x01 \x03(\tR\afolders\"}\n" +
	"\x13PublicDocsListNotes\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x1aG\n" +
	"\bResponse\x12;\n" +
	"\x05notes\x18\x01 \x03(\v2%.artel_public_docs.PublicDocsNoteItemR\x05notes\"l\n" +
	"\x11PublicDocsGetNote\x1a1\n" +
	"\aRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"S\n" +
	"\x12PublicDocsListTags\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2\xdf\x05\n" +
	"\rPublicDocsAPI\x12\x8a\x01\n" +
	"\x0eGetVaultBySlug\x12).artel_public_docs.GetVaultBySlug.Request\x1a*.artel_public_docs.GetVaultBySlug.Response\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/public-docs/vault\x12\x97\x01\n" +
	"\vListFolders\x120.artel_public_docs.PublicDocsListFolders.Request\x1a1.artel_public_docs.PublicDocsListFolders.Response\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/public-docs/folders\x12\x8e\x01\n" +
	"\tListNotes\x12..artel_public_docs.PublicDocsListNotes.Request\x1a/.artel_public_docs.PublicDocsListNotes.Response\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/public-docs/list\x12\x87\x01\n" +
	"\aGetNote\x12,.artel_public_docs.PublicDocsGetNote.Request\x1a-.artel_public_docs.PublicDocsGetNote.Response\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/public-docs/get\x12\x8b\x01\n" +
	"\bListTags\x12-.artel_public_docs.PublicDocsListTags.Request\x1a..artel_public_docs.PublicDocsListTags.Response\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/public-docs/tagsB\x1a\x92\x82\x19\n" +
	"@artel/apiZ\n" +
	"/artel_apib\x06proto3"

var (
	file_public_docs_proto_rawDescOnce sync.Once
	file_public_docs_proto_rawDescData []byte
)

func file_public_docs_proto_rawDescGZIP() []byte {
	file_public_docs_proto_rawDescOnce.Do(func() {
		file_public_docs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_docs_proto_rawDesc), len(file_public_docs_proto_rawDesc)))
	})
	return file_public_docs_proto_rawDescData
}

var file_public_docs_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_public_docs_proto_goTypes = []any{
	(*GetVaultBySlug)(nil),                 // 0: artel_public_docs.GetVaultBySlug
	(*PublicDocsNoteItem)(nil),             // 1: artel_public_docs.PublicDocsNoteItem
	(*PublicDocsListFolders)(nil),          // 2: artel_public_docs.PublicDocsListFolders
	(*PublicDocsListNotes)(nil),            // 3: artel_public_docs.PublicDocsListNotes
	(*PublicDocsGetNote)(nil),              // 4: artel_public_docs.PublicDocsGetNote
	(*PublicDocsListTags)(nil),             // 5: artel_public_docs.PublicDocsListTags
	(*GetVaultBySlug_Request)(nil),         // 6: artel_public_docs.GetVaultBySlug.Request
	(*GetVaultBySlug_Response)(nil),        // 7: artel_public_docs.GetVaultBySlug.Response
	(*PublicDocsListFolders_Request)(nil),  // 8: artel_public_docs.PublicDocsListFolders.Request
	(*PublicDocsListFolders_Response)(nil), // 9: artel_public_docs.PublicDocsListFolders.Response
	(*PublicDocsListNotes_Request)(nil),    // 10: artel_public_docs.PublicDocsListNotes.Request
	(*PublicDocsListNotes_Response)(nil),   // 11: artel_public_docs.PublicDocsListNotes.Response
	(*PublicDocsGetNote_Request)(nil),      // 12: artel_public_docs.PublicDocsGetNote.Request
	(*PublicDocsGetNote_Response)(nil),     // 13: artel_public_docs.PublicDocsGetNote.Response
	(*PublicDocsListTags_Request)(nil),     // 14: artel_public_docs.PublicDocsListTags.Request
	(*PublicDocsListTags_Response)(nil),    // 15: artel_public_docs.PublicDocsListTags.Response
}
var file_public_docs_proto_depIdxs = []int32{
	1,  // 0: artel_public_docs.PublicDocsListNotes.Response.notes:type_name -> artel_public_docs.PublicDocsNoteItem
	6,  // 1: artel_public_docs.PublicDocsAPI.GetVaultBySlug:input_type -> artel_public_docs.GetVaultBySlug.Request
	8,  // 2: artel_public_docs.PublicDocsAPI.ListFolders:input_type -> artel_public_docs.PublicDocsListFolders.Request
	10, // 3: artel_public_docs.PublicDocsAPI.ListNotes:input_type -> artel_public_docs.PublicDocsListNotes.Request
	12, // 4: artel_public_docs.PublicDocsAPI.GetNote:input_type -> artel_public_docs.PublicDocsGetNote.Request
	14, // 5: artel_public_docs.PublicDocsAPI.ListTags:input_type -> artel_public_docs.PublicDocsListTags.Request
	7,  // 6: artel_public_docs.PublicDocsAPI.GetVaultBySlug:output_type -> artel_public_docs.GetVaultBySlug.Response
	9,  // 7: artel_public_docs.PublicDocsAPI.ListFolders:output_type -> artel_public_docs.PublicDocsListFolders.Response
	11, // 8: artel_public_docs.PublicDocsAPI.ListNotes:output_type -> artel_public_docs.PublicDocsListNotes.Response
	13, // 9: artel_public_docs.PublicDocsAPI.GetNote:output_type -> artel_public_docs.PublicDocsGetNote.Response
	15, // 10: artel_public_docs.PublicDocsAPI.ListTags:output_type -> artel_public_docs.PublicDocsListTags.Response
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_public_docs_proto_init() }
func file_public_docs_proto_init() {
	if File_public_docs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_docs_proto_rawDesc), len(file_public_docs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_docs_proto_goTypes,
		DependencyIndexes: file_public_docs_proto_depIdxs,
		MessageInfos:      file_public_docs_proto_msgTypes,
	}.Build()
	File_public_docs_proto = out.File
	file_public_docs_proto_goTypes = nil
	file_public_docs_proto_depIdxs = nil
}
