// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: public_docs.proto

package artel_api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicDocsAPI_GetVaultBySlug_FullMethodName = "/artel_public_docs.PublicDocsAPI/GetVaultBySlug"
	PublicDocsAPI_ListFolders_FullMethodName    = "/artel_public_docs.PublicDocsAPI/ListFolders"
	PublicDocsAPI_ListNotes_FullMethodName      = "/artel_public_docs.PublicDocsAPI/ListNotes"
	PublicDocsAPI_GetNote_FullMethodName        = "/artel_public_docs.PublicDocsAPI/GetNote"
	PublicDocsAPI_ListTags_FullMethodName       = "/artel_public_docs.PublicDocsAPI/ListTags"
)

// PublicDocsAPIClient is the client API for PublicDocsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PublicDocsAPI is the anonymous, auth-exempt read surface for the /docs/:slug viewer
// (see docs/public_vaults.md). Every RPC here independently resolves the target vault via its
// slug and only ever returns data when the vault is published (vaults.is_public); it never
// consults vault_members or user_context. Callers are not authenticated — do not add anything
// here that requires a user identity or that can mutate state. Registered as an
// auth-ignored-paths entry in internal/app/custom.go so the auth interceptor lets these
// through with no token required.
//
// Request/response message names below are prefixed with PublicDocs (rather than reusing
// notes.proto's ListFolders/ListNotes/GetNote/ListTags/NoteItem names) because moti generates
// every api/grpc/*.proto file into the single Go package internal/api/server/artel_api — reusing
// an unprefixed name here would collide with the Go type generated for the equivalent NotesAPI
// message.
type PublicDocsAPIClient interface {
	GetVaultBySlug(ctx context.Context, in *GetVaultBySlug_Request, opts ...grpc.CallOption) (*GetVaultBySlug_Response, error)
	ListFolders(ctx context.Context, in *PublicDocsListFolders_Request, opts ...grpc.CallOption) (*PublicDocsListFolders_Response, error)
	ListNotes(ctx context.Context, in *PublicDocsListNotes_Request, opts ...grpc.CallOption) (*PublicDocsListNotes_Response, error)
	GetNote(ctx context.Context, in *PublicDocsGetNote_Request, opts ...grpc.CallOption) (*PublicDocsGetNote_Response, error)
	ListTags(ctx context.Context, in *PublicDocsListTags_Request, opts ...grpc.CallOption) (*PublicDocsListTags_Response, error)
}

type publicDocsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicDocsAPIClient(cc grpc.ClientConnInterface) PublicDocsAPIClient {
	return &publicDocsAPIClient{cc}
}

func (c *publicDocsAPIClient) GetVaultBySlug(ctx context.Context, in *GetVaultBySlug_Request, opts ...grpc.CallOption) (*GetVaultBySlug_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVaultBySlug_Response)
	err := c.cc.Invoke(ctx, PublicDocsAPI_GetVaultBySlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicDocsAPIClient) ListFolders(ctx context.Context, in *PublicDocsListFolders_Request, opts ...grpc.CallOption) (*PublicDocsListFolders_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicDocsListFolders_Response)
	err := c.cc.Invoke(ctx, PublicDocsAPI_ListFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicDocsAPIClient) ListNotes(ctx context.Context, in *PublicDocsListNotes_Request, opts ...grpc.CallOption) (*PublicDocsListNotes_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicDocsListNotes_Response)
	err := c.cc.Invoke(ctx, PublicDocsAPI_ListNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicDocsAPIClient) GetNote(ctx context.Context, in *PublicDocsGetNote_Request, opts ...grpc.CallOption) (*PublicDocsGetNote_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicDocsGetNote_Response)
	err := c.cc.Invoke(ctx, PublicDocsAPI_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicDocsAPIClient) ListTags(ctx context.Context, in *PublicDocsListTags_Request, opts ...grpc.CallOption) (*PublicDocsListTags_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicDocsListTags_Response)
	err := c.cc.Invoke(ctx, PublicDocsAPI_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicDocsAPIServer is the server API for PublicDocsAPI service.
// All implementations must embed UnimplementedPublicDocsAPIServer
// for forward compatibility.
//
// PublicDocsAPI is the anonymous, auth-exempt read surface for the /docs/:slug viewer
// (see docs/public_vaults.md). Every RPC here independently resolves the target vault via its
// slug and only ever returns data when the vault is published (vaults.is_public); it never
// consults vault_members or user_context. Callers are not authenticated — do not add anything
// here that requires a user identity or that can mutate state. Registered as an
// auth-ignored-paths entry in internal/app/custom.go so the auth interceptor lets these
// through with no token required.
//
// Request/response message names below are prefixed with PublicDocs (rather than reusing
// notes.proto's ListFolders/ListNotes/GetNote/ListTags/NoteItem names) because moti generates
// every api/grpc/*.proto file into the single Go package internal/api/server/artel_api — reusing
// an unprefixed name here would collide with the Go type generated for the equivalent NotesAPI
// message.
type PublicDocsAPIServer interface {
	GetVaultBySlug(context.Context, *GetVaultBySlug_Request) (*GetVaultBySlug_Response, error)
	ListFolders(context.Context, *PublicDocsListFolders_Request) (*PublicDocsListFolders_Response, error)
	ListNotes(context.Context, *PublicDocsListNotes_Request) (*PublicDocsListNotes_Response, error)
	GetNote(context.Context, *PublicDocsGetNote_Request) (*PublicDocsGetNote_Response, error)
	ListTags(context.Context, *PublicDocsListTags_Request) (*PublicDocsListTags_Response, error)
	mustEmbedUnimplementedPublicDocsAPIServer()
}

// UnimplementedPublicDocsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicDocsAPIServer struct{}

func (UnimplementedPublicDocsAPIServer) GetVaultBySlug(context.Context, *GetVaultBySlug_Request) (*GetVaultBySlug_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVaultBySlug not implemented")
}
func (UnimplementedPublicDocsAPIServer) ListFolders(context.Context, *PublicDocsListFolders_Request) (*PublicDocsListFolders_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFolders not implemented")
}
func (UnimplementedPublicDocsAPIServer) ListNotes(context.Context, *PublicDocsListNotes_Request) (*PublicDocsListNotes_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedPublicDocsAPIServer) GetNote(context.Context, *PublicDocsGetNote_Request) (*PublicDocsGetNote_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedPublicDocsAPIServer) ListTags(context.Context, *PublicDocsListTags_Request) (*PublicDocsListTags_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedPublicDocsAPIServer) mustEmbedUnimplementedPublicDocsAPIServer() {}
func (UnimplementedPublicDocsAPIServer) testEmbeddedByValue()                       {}

// UnsafePublicDocsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicDocsAPIServer will
// result in compilation errors.
type UnsafePublicDocsAPIServer interface {
	mustEmbedUnimplementedPublicDocsAPIServer()
}

func RegisterPublicDocsAPIServer(s grpc.ServiceRegistrar, srv PublicDocsAPIServer) {
	// If the following call panics, it indicates UnimplementedPublicDocsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicDocsAPI_ServiceDesc, srv)
}

func _PublicDocsAPI_GetVaultBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVaultBySlug_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicDocsAPIServer).GetVaultBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicDocsAPI_GetVaultBySlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicDocsAPIServer).GetVaultBySlug(ctx, req.(*GetVaultBySlug_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicDocsAPI_ListFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicDocsListFolders_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicDocsAPIServer).ListFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicDocsAPI_ListFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicDocsAPIServer).ListFolders(ctx, req.(*PublicDocsListFolders_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicDocsAPI_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicDocsListNotes_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicDocsAPIServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicDocsAPI_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicDocsAPIServer).ListNotes(ctx, req.(*PublicDocsListNotes_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicDocsAPI_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicDocsGetNote_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicDocsAPIServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicDocsAPI_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicDocsAPIServer).GetNote(ctx, req.(*PublicDocsGetNote_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicDocsAPI_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicDocsListTags_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicDocsAPIServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicDocsAPI_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicDocsAPIServer).ListTags(ctx, req.(*PublicDocsListTags_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicDocsAPI_ServiceDesc is the grpc.ServiceDesc for PublicDocsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicDocsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artel_public_docs.PublicDocsAPI",
	HandlerType: (*PublicDocsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVaultBySlug",
			Handler:    _PublicDocsAPI_GetVaultBySlug_Handler,
		},
		{
			MethodName: "ListFolders",
			Handler:    _PublicDocsAPI_ListFolders_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _PublicDocsAPI_ListNotes_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _PublicDocsAPI_GetNote_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _PublicDocsAPI_ListTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public_docs.proto",
}
