// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: setup_wizard.proto

package artel_api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SetupWizardAPI_GetStatus_FullMethodName              = "/artel_setup_wizard.SetupWizardAPI/GetStatus"
	SetupWizardAPI_SubmitToken_FullMethodName            = "/artel_setup_wizard.SetupWizardAPI/SubmitToken"
	SetupWizardAPI_SelectAuthMethods_FullMethodName      = "/artel_setup_wizard.SetupWizardAPI/SelectAuthMethods"
	SetupWizardAPI_SelectRegistrationMode_FullMethodName = "/artel_setup_wizard.SetupWizardAPI/SelectRegistrationMode"
	SetupWizardAPI_CompleteSetup_FullMethodName          = "/artel_setup_wizard.SetupWizardAPI/CompleteSetup"
)

// SetupWizardAPIClient is the client API for SetupWizardAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SetupWizardAPIClient interface {
	GetStatus(ctx context.Context, in *GetStatus_Request, opts ...grpc.CallOption) (*GetStatus_Response, error)
	SubmitToken(ctx context.Context, in *SubmitToken_Request, opts ...grpc.CallOption) (*SubmitToken_Response, error)
	SelectAuthMethods(ctx context.Context, in *SelectAuthMethods_Request, opts ...grpc.CallOption) (*SelectAuthMethods_Response, error)
	SelectRegistrationMode(ctx context.Context, in *SelectRegistrationMode_Request, opts ...grpc.CallOption) (*SelectRegistrationMode_Response, error)
	CompleteSetup(ctx context.Context, in *CompleteSetup_Request, opts ...grpc.CallOption) (*CompleteSetup_Response, error)
}

type setupWizardAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSetupWizardAPIClient(cc grpc.ClientConnInterface) SetupWizardAPIClient {
	return &setupWizardAPIClient{cc}
}

func (c *setupWizardAPIClient) GetStatus(ctx context.Context, in *GetStatus_Request, opts ...grpc.CallOption) (*GetStatus_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatus_Response)
	err := c.cc.Invoke(ctx, SetupWizardAPI_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setupWizardAPIClient) SubmitToken(ctx context.Context, in *SubmitToken_Request, opts ...grpc.CallOption) (*SubmitToken_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitToken_Response)
	err := c.cc.Invoke(ctx, SetupWizardAPI_SubmitToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setupWizardAPIClient) SelectAuthMethods(ctx context.Context, in *SelectAuthMethods_Request, opts ...grpc.CallOption) (*SelectAuthMethods_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectAuthMethods_Response)
	err := c.cc.Invoke(ctx, SetupWizardAPI_SelectAuthMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setupWizardAPIClient) SelectRegistrationMode(ctx context.Context, in *SelectRegistrationMode_Request, opts ...grpc.CallOption) (*SelectRegistrationMode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectRegistrationMode_Response)
	err := c.cc.Invoke(ctx, SetupWizardAPI_SelectRegistrationMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setupWizardAPIClient) CompleteSetup(ctx context.Context, in *CompleteSetup_Request, opts ...grpc.CallOption) (*CompleteSetup_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteSetup_Response)
	err := c.cc.Invoke(ctx, SetupWizardAPI_CompleteSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetupWizardAPIServer is the server API for SetupWizardAPI service.
// All implementations must embed UnimplementedSetupWizardAPIServer
// for forward compatibility.
type SetupWizardAPIServer interface {
	GetStatus(context.Context, *GetStatus_Request) (*GetStatus_Response, error)
	SubmitToken(context.Context, *SubmitToken_Request) (*SubmitToken_Response, error)
	SelectAuthMethods(context.Context, *SelectAuthMethods_Request) (*SelectAuthMethods_Response, error)
	SelectRegistrationMode(context.Context, *SelectRegistrationMode_Request) (*SelectRegistrationMode_Response, error)
	CompleteSetup(context.Context, *CompleteSetup_Request) (*CompleteSetup_Response, error)
	mustEmbedUnimplementedSetupWizardAPIServer()
}

// UnimplementedSetupWizardAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSetupWizardAPIServer struct{}

func (UnimplementedSetupWizardAPIServer) GetStatus(context.Context, *GetStatus_Request) (*GetStatus_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSetupWizardAPIServer) SubmitToken(context.Context, *SubmitToken_Request) (*SubmitToken_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitToken not implemented")
}
func (UnimplementedSetupWizardAPIServer) SelectAuthMethods(context.Context, *SelectAuthMethods_Request) (*SelectAuthMethods_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectAuthMethods not implemented")
}
func (UnimplementedSetupWizardAPIServer) SelectRegistrationMode(context.Context, *SelectRegistrationMode_Request) (*SelectRegistrationMode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectRegistrationMode not implemented")
}
func (UnimplementedSetupWizardAPIServer) CompleteSetup(context.Context, *CompleteSetup_Request) (*CompleteSetup_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteSetup not implemented")
}
func (UnimplementedSetupWizardAPIServer) mustEmbedUnimplementedSetupWizardAPIServer() {}
func (UnimplementedSetupWizardAPIServer) testEmbeddedByValue()                        {}

// UnsafeSetupWizardAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SetupWizardAPIServer will
// result in compilation errors.
type UnsafeSetupWizardAPIServer interface {
	mustEmbedUnimplementedSetupWizardAPIServer()
}

func RegisterSetupWizardAPIServer(s grpc.ServiceRegistrar, srv SetupWizardAPIServer) {
	// If the following call panics, it indicates UnimplementedSetupWizardAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SetupWizardAPI_ServiceDesc, srv)
}

func _SetupWizardAPI_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatus_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupWizardAPIServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupWizardAPI_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupWizardAPIServer).GetStatus(ctx, req.(*GetStatus_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetupWizardAPI_SubmitToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitToken_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupWizardAPIServer).SubmitToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupWizardAPI_SubmitToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupWizardAPIServer).SubmitToken(ctx, req.(*SubmitToken_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetupWizardAPI_SelectAuthMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectAuthMethods_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupWizardAPIServer).SelectAuthMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupWizardAPI_SelectAuthMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupWizardAPIServer).SelectAuthMethods(ctx, req.(*SelectAuthMethods_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetupWizardAPI_SelectRegistrationMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRegistrationMode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupWizardAPIServer).SelectRegistrationMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupWizardAPI_SelectRegistrationMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupWizardAPIServer).SelectRegistrationMode(ctx, req.(*SelectRegistrationMode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SetupWizardAPI_CompleteSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSetup_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetupWizardAPIServer).CompleteSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SetupWizardAPI_CompleteSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetupWizardAPIServer).CompleteSetup(ctx, req.(*CompleteSetup_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SetupWizardAPI_ServiceDesc is the grpc.ServiceDesc for SetupWizardAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SetupWizardAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artel_setup_wizard.SetupWizardAPI",
	HandlerType: (*SetupWizardAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _SetupWizardAPI_GetStatus_Handler,
		},
		{
			MethodName: "SubmitToken",
			Handler:    _SetupWizardAPI_SubmitToken_Handler,
		},
		{
			MethodName: "SelectAuthMethods",
			Handler:    _SetupWizardAPI_SelectAuthMethods_Handler,
		},
		{
			MethodName: "SelectRegistrationMode",
			Handler:    _SetupWizardAPI_SelectRegistrationMode_Handler,
		},
		{
			MethodName: "CompleteSetup",
			Handler:    _SetupWizardAPI_CompleteSetup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "setup_wizard.proto",
}
