// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: user_settings.proto

package artel_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettings) Reset() {
	*x = GetUserSettings{}
	mi := &file_user_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettings) ProtoMessage() {}

func (x *GetUserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettings.ProtoReflect.Descriptor instead.
func (*GetUserSettings) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{0}
}

type SetLikedModels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLikedModels) Reset() {
	*x = SetLikedModels{}
	mi := &file_user_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLikedModels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLikedModels) ProtoMessage() {}

func (x *SetLikedModels) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLikedModels.ProtoReflect.Descriptor instead.
func (*SetLikedModels) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{1}
}

type SetLastUsedModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLastUsedModel) Reset() {
	*x = SetLastUsedModel{}
	mi := &file_user_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLastUsedModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLastUsedModel) ProtoMessage() {}

func (x *SetLastUsedModel) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLastUsedModel.ProtoReflect.Descriptor instead.
func (*SetLastUsedModel) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{2}
}

type GetUserSettings_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettings_Request) Reset() {
	*x = GetUserSettings_Request{}
	mi := &file_user_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettings_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettings_Request) ProtoMessage() {}

func (x *GetUserSettings_Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettings_Request.ProtoReflect.Descriptor instead.
func (*GetUserSettings_Request) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{0, 0}
}

type GetUserSettings_Response struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserPrompt            string                 `protobuf:"bytes,1,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"`
	LikedOpenrouterModels []string               `protobuf:"bytes,2,rep,name=liked_openrouter_models,json=likedOpenrouterModels,proto3" json:"liked_openrouter_models,omitempty"`
	LastUsedModel         string                 `protobuf:"bytes,3,opt,name=last_used_model,json=lastUsedModel,proto3" json:"last_used_model,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetUserSettings_Response) Reset() {
	*x = GetUserSettings_Response{}
	mi := &file_user_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettings_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettings_Response) ProtoMessage() {}

func (x *GetUserSettings_Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettings_Response.ProtoReflect.Descriptor instead.
func (*GetUserSettings_Response) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetUserSettings_Response) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *GetUserSettings_Response) GetLikedOpenrouterModels() []string {
	if x != nil {
		return x.LikedOpenrouterModels
	}
	return nil
}

func (x *GetUserSettings_Response) GetLastUsedModel() string {
	if x != nil {
		return x.LastUsedModel
	}
	return ""
}

type SetLikedModels_Request struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LikedOpenrouterModels []string               `protobuf:"bytes,1,rep,name=liked_openrouter_models,json=likedOpenrouterModels,proto3" json:"liked_openrouter_models,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SetLikedModels_Request) Reset() {
	*x = SetLikedModels_Request{}
	mi := &file_user_settings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLikedModels_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLikedModels_Request) ProtoMessage() {}

func (x *SetLikedModels_Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLikedModels_Request.ProtoReflect.Descriptor instead.
func (*SetLikedModels_Request) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SetLikedModels_Request) GetLikedOpenrouterModels() []string {
	if x != nil {
		return x.LikedOpenrouterModels
	}
	return nil
}

type SetLikedModels_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLikedModels_Response) Reset() {
	*x = SetLikedModels_Response{}
	mi := &file_user_settings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLikedModels_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLikedModels_Response) ProtoMessage() {}

func (x *SetLikedModels_Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLikedModels_Response.ProtoReflect.Descriptor instead.
func (*SetLikedModels_Response) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{1, 1}
}

type SetLastUsedModel_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLastUsedModel_Request) Reset() {
	*x = SetLastUsedModel_Request{}
	mi := &file_user_settings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLastUsedModel_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLastUsedModel_Request) ProtoMessage() {}

func (x *SetLastUsedModel_Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLastUsedModel_Request.ProtoReflect.Descriptor instead.
func (*SetLastUsedModel_Request) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SetLastUsedModel_Request) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SetLastUsedModel_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLastUsedModel_Response) Reset() {
	*x = SetLastUsedModel_Response{}
	mi := &file_user_settings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLastUsedModel_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLastUsedModel_Response) ProtoMessage() {}

func (x *SetLastUsedModel_Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_settings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLastUsedModel_Response.ProtoReflect.Descriptor instead.
func (*SetLastUsedModel_Response) Descriptor() ([]byte, []int) {
	return file_user_settings_proto_rawDescGZIP(), []int{2, 1}
}

var File_user_settings_proto protoreflect.FileDescriptor

const file_user_settings_proto_rawDesc = "" +
	"\n" +
	"\x13user_settings.proto\x12\tartel_api\x1a\x1cgoogle/api/annotations.proto\"\xaa\x01\n" +
	"\x0fGetUserSettings\x1a\t\n" +
	"\aRequest\x1a\x8b\x01\n" +
	"\bResponse\x12\x1f\n" +
	"\vuser_prompt\x18\x01 \x01(\tR\n" +
	"userPrompt\x126\n" +
	"\x17liked_openrouter_models\x18\x02 \x03(\tR\x15likedOpenrouterModels\x12&\n" +
	"\x0flast_used_model\x18\x03 \x01(\tR\rlastUsedModel\"_\n" +
	"\x0eSetLikedModels\x1aA\n" +
	"\aRequest\x126\n" +
	"\x17liked_openrouter_models\x18\x01 \x03(\tR\x15likedOpenrouterModels\x1a\n" +
	"\n" +
	"\bResponse\"?\n" +
	"\x10SetLastUsedModel\x1a\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x1a\n" +
	"\n" +
	"\bResponse2\xaa\x03\n" +
	"\x0fUserSettingsAPI\x12z\n" +
	"\x0fGetUserSettings\x12\".artel_api.GetUserSettings.Request\x1a#.artel_api.GetUserSettings.Response\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/user-settings/get\x12\x87\x01\n" +
	"\x0eSetLikedModels\x12!.artel_api.SetLikedModels.Request\x1a\".artel_api.SetLikedModels.Response\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/user-settings/set-liked-models\x12\x90\x01\n" +
	"\x10SetLastUsedModel\x12#.artel_api.SetLastUsedModel.Request\x1a$.artel_api.SetLastUsedModel.Response\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/user-settings/set-last-used-modelB\fZ\n" +
	"/artel_apib\x06proto3"

var (
	file_user_settings_proto_rawDescOnce sync.Once
	file_user_settings_proto_rawDescData []byte
)

func file_user_settings_proto_rawDescGZIP() []byte {
	file_user_settings_proto_rawDescOnce.Do(func() {
		file_user_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_settings_proto_rawDesc), len(file_user_settings_proto_rawDesc)))
	})
	return file_user_settings_proto_rawDescData
}

var file_user_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_settings_proto_goTypes = []any{
	(*GetUserSettings)(nil),           // 0: artel_api.GetUserSettings
	(*SetLikedModels)(nil),            // 1: artel_api.SetLikedModels
	(*SetLastUsedModel)(nil),          // 2: artel_api.SetLastUsedModel
	(*GetUserSettings_Request)(nil),   // 3: artel_api.GetUserSettings.Request
	(*GetUserSettings_Response)(nil),  // 4: artel_api.GetUserSettings.Response
	(*SetLikedModels_Request)(nil),    // 5: artel_api.SetLikedModels.Request
	(*SetLikedModels_Response)(nil),   // 6: artel_api.SetLikedModels.Response
	(*SetLastUsedModel_Request)(nil),  // 7: artel_api.SetLastUsedModel.Request
	(*SetLastUsedModel_Response)(nil), // 8: artel_api.SetLastUsedModel.Response
}
var file_user_settings_proto_depIdxs = []int32{
	3, // 0: artel_api.UserSettingsAPI.GetUserSettings:input_type -> artel_api.GetUserSettings.Request
	5, // 1: artel_api.UserSettingsAPI.SetLikedModels:input_type -> artel_api.SetLikedModels.Request
	7, // 2: artel_api.UserSettingsAPI.SetLastUsedModel:input_type -> artel_api.SetLastUsedModel.Request
	4, // 3: artel_api.UserSettingsAPI.GetUserSettings:output_type -> artel_api.GetUserSettings.Response
	6, // 4: artel_api.UserSettingsAPI.SetLikedModels:output_type -> artel_api.SetLikedModels.Response
	8, // 5: artel_api.UserSettingsAPI.SetLastUsedModel:output_type -> artel_api.SetLastUsedModel.Response
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_settings_proto_init() }
func file_user_settings_proto_init() {
	if File_user_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_settings_proto_rawDesc), len(file_user_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_settings_proto_goTypes,
		DependencyIndexes: file_user_settings_proto_depIdxs,
		MessageInfos:      file_user_settings_proto_msgTypes,
	}.Build()
	File_user_settings_proto = out.File
	file_user_settings_proto_goTypes = nil
	file_user_settings_proto_depIdxs = nil
}
