// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: vaults.proto

package artel_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVault) Reset() {
	*x = CreateVault{}
	mi := &file_vaults_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVault) ProtoMessage() {}

func (x *CreateVault) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVault.ProtoReflect.Descriptor instead.
func (*CreateVault) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{0}
}

type GetVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVault) Reset() {
	*x = GetVault{}
	mi := &file_vaults_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVault) ProtoMessage() {}

func (x *GetVault) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVault.ProtoReflect.Descriptor instead.
func (*GetVault) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{1}
}

type ListVaults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVaults) Reset() {
	*x = ListVaults{}
	mi := &file_vaults_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVaults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVaults) ProtoMessage() {}

func (x *ListVaults) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVaults.ProtoReflect.Descriptor instead.
func (*ListVaults) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{2}
}

type DeleteVault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVault) Reset() {
	*x = DeleteVault{}
	mi := &file_vaults_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVault) ProtoMessage() {}

func (x *DeleteVault) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVault.ProtoReflect.Descriptor instead.
func (*DeleteVault) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{3}
}

type AddMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMember) Reset() {
	*x = AddMember{}
	mi := &file_vaults_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMember) ProtoMessage() {}

func (x *AddMember) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMember.ProtoReflect.Descriptor instead.
func (*AddMember) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{4}
}

type RemoveMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMember) Reset() {
	*x = RemoveMember{}
	mi := &file_vaults_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMember) ProtoMessage() {}

func (x *RemoveMember) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMember.ProtoReflect.Descriptor instead.
func (*RemoveMember) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{5}
}

type ListMembers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembers) Reset() {
	*x = ListMembers{}
	mi := &file_vaults_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembers) ProtoMessage() {}

func (x *ListMembers) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembers.ProtoReflect.Descriptor instead.
func (*ListMembers) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{6}
}

type CreateInviteLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteLink) Reset() {
	*x = CreateInviteLink{}
	mi := &file_vaults_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteLink) ProtoMessage() {}

func (x *CreateInviteLink) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteLink.ProtoReflect.Descriptor instead.
func (*CreateInviteLink) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{7}
}

type ListInviteLinks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInviteLinks) Reset() {
	*x = ListInviteLinks{}
	mi := &file_vaults_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInviteLinks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInviteLinks) ProtoMessage() {}

func (x *ListInviteLinks) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInviteLinks.ProtoReflect.Descriptor instead.
func (*ListInviteLinks) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{8}
}

type RevokeInviteLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInviteLink) Reset() {
	*x = RevokeInviteLink{}
	mi := &file_vaults_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteLink) ProtoMessage() {}

func (x *RevokeInviteLink) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInviteLink.ProtoReflect.Descriptor instead.
func (*RevokeInviteLink) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{9}
}

type AcceptInvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvite) Reset() {
	*x = AcceptInvite{}
	mi := &file_vaults_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvite) ProtoMessage() {}

func (x *AcceptInvite) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvite.ProtoReflect.Descriptor instead.
func (*AcceptInvite) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{10}
}

type LinkS3Bucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkS3Bucket) Reset() {
	*x = LinkS3Bucket{}
	mi := &file_vaults_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkS3Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkS3Bucket) ProtoMessage() {}

func (x *LinkS3Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkS3Bucket.ProtoReflect.Descriptor instead.
func (*LinkS3Bucket) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{11}
}

type UnlinkS3Bucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkS3Bucket) Reset() {
	*x = UnlinkS3Bucket{}
	mi := &file_vaults_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkS3Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkS3Bucket) ProtoMessage() {}

func (x *UnlinkS3Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkS3Bucket.ProtoReflect.Descriptor instead.
func (*UnlinkS3Bucket) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{12}
}

type SetVaultBinaryStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVaultBinaryStorage) Reset() {
	*x = SetVaultBinaryStorage{}
	mi := &file_vaults_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVaultBinaryStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVaultBinaryStorage) ProtoMessage() {}

func (x *SetVaultBinaryStorage) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVaultBinaryStorage.ProtoReflect.Descriptor instead.
func (*SetVaultBinaryStorage) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{13}
}

type StartWorkbench struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkbench) Reset() {
	*x = StartWorkbench{}
	mi := &file_vaults_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkbench) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkbench) ProtoMessage() {}

func (x *StartWorkbench) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkbench.ProtoReflect.Descriptor instead.
func (*StartWorkbench) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{14}
}

type StopWorkbench struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkbench) Reset() {
	*x = StopWorkbench{}
	mi := &file_vaults_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkbench) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkbench) ProtoMessage() {}

func (x *StopWorkbench) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkbench.ProtoReflect.Descriptor instead.
func (*StopWorkbench) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{15}
}

type VaultItem struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DbUrl                 string                 `protobuf:"bytes,3,opt,name=db_url,json=dbUrl,proto3" json:"db_url,omitempty"`
	LivesyncPassphrase    string                 `protobuf:"bytes,4,opt,name=livesync_passphrase,json=livesyncPassphrase,proto3" json:"livesync_passphrase,omitempty"`
	S3InstanceId          string                 `protobuf:"bytes,5,opt,name=s3_instance_id,json=s3InstanceId,proto3" json:"s3_instance_id,omitempty"`
	S3BucketName          string                 `protobuf:"bytes,6,opt,name=s3_bucket_name,json=s3BucketName,proto3" json:"s3_bucket_name,omitempty"`
	UseCouchdbForBinaries bool                   `protobuf:"varint,7,opt,name=use_couchdb_for_binaries,json=useCouchdbForBinaries,proto3" json:"use_couchdb_for_binaries,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VaultItem) Reset() {
	*x = VaultItem{}
	mi := &file_vaults_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultItem) ProtoMessage() {}

func (x *VaultItem) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultItem.ProtoReflect.Descriptor instead.
func (*VaultItem) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{16}
}

func (x *VaultItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VaultItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VaultItem) GetDbUrl() string {
	if x != nil {
		return x.DbUrl
	}
	return ""
}

func (x *VaultItem) GetLivesyncPassphrase() string {
	if x != nil {
		return x.LivesyncPassphrase
	}
	return ""
}

func (x *VaultItem) GetS3InstanceId() string {
	if x != nil {
		return x.S3InstanceId
	}
	return ""
}

func (x *VaultItem) GetS3BucketName() string {
	if x != nil {
		return x.S3BucketName
	}
	return ""
}

func (x *VaultItem) GetUseCouchdbForBinaries() bool {
	if x != nil {
		return x.UseCouchdbForBinaries
	}
	return false
}

type VaultMemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultMemberInfo) Reset() {
	*x = VaultMemberInfo{}
	mi := &file_vaults_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultMemberInfo) ProtoMessage() {}

func (x *VaultMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultMemberInfo.ProtoReflect.Descriptor instead.
func (*VaultMemberInfo) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{17}
}

func (x *VaultMemberInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VaultMemberInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VaultMemberInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VaultMemberInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VaultMemberInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type VaultInviteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VaultId       string                 `protobuf:"bytes,2,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Revoked       bool                   `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultInviteItem) Reset() {
	*x = VaultInviteItem{}
	mi := &file_vaults_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultInviteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultInviteItem) ProtoMessage() {}

func (x *VaultInviteItem) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultInviteItem.ProtoReflect.Descriptor instead.
func (*VaultInviteItem) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{18}
}

func (x *VaultInviteItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VaultInviteItem) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultInviteItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *VaultInviteItem) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VaultInviteItem) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *VaultInviteItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateVault_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVault_Request) Reset() {
	*x = CreateVault_Request{}
	mi := &file_vaults_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVault_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVault_Request) ProtoMessage() {}

func (x *CreateVault_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVault_Request.ProtoReflect.Descriptor instead.
func (*CreateVault_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateVault_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateVault_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DbUrl         string                 `protobuf:"bytes,3,opt,name=db_url,json=dbUrl,proto3" json:"db_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVault_Response) Reset() {
	*x = CreateVault_Response{}
	mi := &file_vaults_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVault_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVault_Response) ProtoMessage() {}

func (x *CreateVault_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVault_Response.ProtoReflect.Descriptor instead.
func (*CreateVault_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateVault_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateVault_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVault_Response) GetDbUrl() string {
	if x != nil {
		return x.DbUrl
	}
	return ""
}

type GetVault_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVault_Request) Reset() {
	*x = GetVault_Request{}
	mi := &file_vaults_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVault_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVault_Request) ProtoMessage() {}

func (x *GetVault_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVault_Request.ProtoReflect.Descriptor instead.
func (*GetVault_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetVault_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVault_Response struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DbUrl        string                 `protobuf:"bytes,3,opt,name=db_url,json=dbUrl,proto3" json:"db_url,omitempty"`
	S3InstanceId string                 `protobuf:"bytes,4,opt,name=s3_instance_id,json=s3InstanceId,proto3" json:"s3_instance_id,omitempty"`
	S3BucketName string                 `protobuf:"bytes,5,opt,name=s3_bucket_name,json=s3BucketName,proto3" json:"s3_bucket_name,omitempty"`
	// workbench_exists is false when no workbenches row backs this vault yet — either the vault
	// predates this feature, or WorkbenchDockerHost isn't configured for this deployment.
	// workbench_status is only meaningful when workbench_exists is true; one of
	// "created"/"running"/"stopped"/"removed" (see domain.WorkbenchStatus).
	WorkbenchExists bool   `protobuf:"varint,6,opt,name=workbench_exists,json=workbenchExists,proto3" json:"workbench_exists,omitempty"`
	WorkbenchStatus string `protobuf:"bytes,7,opt,name=workbench_status,json=workbenchStatus,proto3" json:"workbench_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetVault_Response) Reset() {
	*x = GetVault_Response{}
	mi := &file_vaults_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVault_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVault_Response) ProtoMessage() {}

func (x *GetVault_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVault_Response.ProtoReflect.Descriptor instead.
func (*GetVault_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetVault_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVault_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVault_Response) GetDbUrl() string {
	if x != nil {
		return x.DbUrl
	}
	return ""
}

func (x *GetVault_Response) GetS3InstanceId() string {
	if x != nil {
		return x.S3InstanceId
	}
	return ""
}

func (x *GetVault_Response) GetS3BucketName() string {
	if x != nil {
		return x.S3BucketName
	}
	return ""
}

func (x *GetVault_Response) GetWorkbenchExists() bool {
	if x != nil {
		return x.WorkbenchExists
	}
	return false
}

func (x *GetVault_Response) GetWorkbenchStatus() string {
	if x != nil {
		return x.WorkbenchStatus
	}
	return ""
}

type ListVaults_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVaults_Request) Reset() {
	*x = ListVaults_Request{}
	mi := &file_vaults_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVaults_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVaults_Request) ProtoMessage() {}

func (x *ListVaults_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVaults_Request.ProtoReflect.Descriptor instead.
func (*ListVaults_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{2, 0}
}

type ListVaults_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vaults        []*VaultItem           `protobuf:"bytes,1,rep,name=vaults,proto3" json:"vaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVaults_Response) Reset() {
	*x = ListVaults_Response{}
	mi := &file_vaults_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVaults_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVaults_Response) ProtoMessage() {}

func (x *ListVaults_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVaults_Response.ProtoReflect.Descriptor instead.
func (*ListVaults_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ListVaults_Response) GetVaults() []*VaultItem {
	if x != nil {
		return x.Vaults
	}
	return nil
}

type DeleteVault_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVault_Request) Reset() {
	*x = DeleteVault_Request{}
	mi := &file_vaults_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVault_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVault_Request) ProtoMessage() {}

func (x *DeleteVault_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVault_Request.ProtoReflect.Descriptor instead.
func (*DeleteVault_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DeleteVault_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteVault_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVault_Response) Reset() {
	*x = DeleteVault_Response{}
	mi := &file_vaults_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVault_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVault_Response) ProtoMessage() {}

func (x *DeleteVault_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVault_Response.ProtoReflect.Descriptor instead.
func (*DeleteVault_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{3, 1}
}

type AddMember_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMember_Request) Reset() {
	*x = AddMember_Request{}
	mi := &file_vaults_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMember_Request) ProtoMessage() {}

func (x *AddMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMember_Request.ProtoReflect.Descriptor instead.
func (*AddMember_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AddMember_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *AddMember_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMember_Request) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMember_Response) Reset() {
	*x = AddMember_Response{}
	mi := &file_vaults_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMember_Response) ProtoMessage() {}

func (x *AddMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMember_Response.ProtoReflect.Descriptor instead.
func (*AddMember_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{4, 1}
}

type RemoveMember_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMember_Request) Reset() {
	*x = RemoveMember_Request{}
	mi := &file_vaults_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMember_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMember_Request) ProtoMessage() {}

func (x *RemoveMember_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMember_Request.ProtoReflect.Descriptor instead.
func (*RemoveMember_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RemoveMember_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *RemoveMember_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveMember_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMember_Response) Reset() {
	*x = RemoveMember_Response{}
	mi := &file_vaults_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMember_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMember_Response) ProtoMessage() {}

func (x *RemoveMember_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMember_Response.ProtoReflect.Descriptor instead.
func (*RemoveMember_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{5, 1}
}

type ListMembers_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembers_Request) Reset() {
	*x = ListMembers_Request{}
	mi := &file_vaults_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembers_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembers_Request) ProtoMessage() {}

func (x *ListMembers_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembers_Request.ProtoReflect.Descriptor instead.
func (*ListMembers_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListMembers_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type ListMembers_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*VaultMemberInfo     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembers_Response) Reset() {
	*x = ListMembers_Response{}
	mi := &file_vaults_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembers_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembers_Response) ProtoMessage() {}

func (x *ListMembers_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembers_Response.ProtoReflect.Descriptor instead.
func (*ListMembers_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{6, 1}
}

func (x *ListMembers_Response) GetMembers() []*VaultMemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateInviteLink_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteLink_Request) Reset() {
	*x = CreateInviteLink_Request{}
	mi := &file_vaults_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteLink_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteLink_Request) ProtoMessage() {}

func (x *CreateInviteLink_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteLink_Request.ProtoReflect.Descriptor instead.
func (*CreateInviteLink_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{7, 0}
}

func (x *CreateInviteLink_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *CreateInviteLink_Request) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateInviteLink_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        *VaultInviteItem       `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteLink_Response) Reset() {
	*x = CreateInviteLink_Response{}
	mi := &file_vaults_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteLink_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteLink_Response) ProtoMessage() {}

func (x *CreateInviteLink_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteLink_Response.ProtoReflect.Descriptor instead.
func (*CreateInviteLink_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{7, 1}
}

func (x *CreateInviteLink_Response) GetInvite() *VaultInviteItem {
	if x != nil {
		return x.Invite
	}
	return nil
}

type ListInviteLinks_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInviteLinks_Request) Reset() {
	*x = ListInviteLinks_Request{}
	mi := &file_vaults_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInviteLinks_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInviteLinks_Request) ProtoMessage() {}

func (x *ListInviteLinks_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInviteLinks_Request.ProtoReflect.Descriptor instead.
func (*ListInviteLinks_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ListInviteLinks_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type ListInviteLinks_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invites       []*VaultInviteItem     `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInviteLinks_Response) Reset() {
	*x = ListInviteLinks_Response{}
	mi := &file_vaults_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInviteLinks_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInviteLinks_Response) ProtoMessage() {}

func (x *ListInviteLinks_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInviteLinks_Response.ProtoReflect.Descriptor instead.
func (*ListInviteLinks_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{8, 1}
}

func (x *ListInviteLinks_Response) GetInvites() []*VaultInviteItem {
	if x != nil {
		return x.Invites
	}
	return nil
}

type RevokeInviteLink_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	InviteId      string                 `protobuf:"bytes,2,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInviteLink_Request) Reset() {
	*x = RevokeInviteLink_Request{}
	mi := &file_vaults_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteLink_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteLink_Request) ProtoMessage() {}

func (x *RevokeInviteLink_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInviteLink_Request.ProtoReflect.Descriptor instead.
func (*RevokeInviteLink_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{9, 0}
}

func (x *RevokeInviteLink_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *RevokeInviteLink_Request) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

type RevokeInviteLink_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInviteLink_Response) Reset() {
	*x = RevokeInviteLink_Response{}
	mi := &file_vaults_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInviteLink_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInviteLink_Response) ProtoMessage() {}

func (x *RevokeInviteLink_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInviteLink_Response.ProtoReflect.Descriptor instead.
func (*RevokeInviteLink_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{9, 1}
}

type AcceptInvite_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvite_Request) Reset() {
	*x = AcceptInvite_Request{}
	mi := &file_vaults_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvite_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvite_Request) ProtoMessage() {}

func (x *AcceptInvite_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvite_Request.ProtoReflect.Descriptor instead.
func (*AcceptInvite_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{10, 0}
}

func (x *AcceptInvite_Request) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AcceptInvite_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvite_Response) Reset() {
	*x = AcceptInvite_Response{}
	mi := &file_vaults_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvite_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvite_Response) ProtoMessage() {}

func (x *AcceptInvite_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvite_Response.ProtoReflect.Descriptor instead.
func (*AcceptInvite_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{10, 1}
}

func (x *AcceptInvite_Response) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type LinkS3Bucket_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	S3InstanceId  string                 `protobuf:"bytes,2,opt,name=s3_instance_id,json=s3InstanceId,proto3" json:"s3_instance_id,omitempty"`
	BucketName    string                 `protobuf:"bytes,3,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkS3Bucket_Request) Reset() {
	*x = LinkS3Bucket_Request{}
	mi := &file_vaults_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkS3Bucket_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkS3Bucket_Request) ProtoMessage() {}

func (x *LinkS3Bucket_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkS3Bucket_Request.ProtoReflect.Descriptor instead.
func (*LinkS3Bucket_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{11, 0}
}

func (x *LinkS3Bucket_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *LinkS3Bucket_Request) GetS3InstanceId() string {
	if x != nil {
		return x.S3InstanceId
	}
	return ""
}

func (x *LinkS3Bucket_Request) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type LinkS3Bucket_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkS3Bucket_Response) Reset() {
	*x = LinkS3Bucket_Response{}
	mi := &file_vaults_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkS3Bucket_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkS3Bucket_Response) ProtoMessage() {}

func (x *LinkS3Bucket_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkS3Bucket_Response.ProtoReflect.Descriptor instead.
func (*LinkS3Bucket_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{11, 1}
}

type UnlinkS3Bucket_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkS3Bucket_Request) Reset() {
	*x = UnlinkS3Bucket_Request{}
	mi := &file_vaults_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkS3Bucket_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkS3Bucket_Request) ProtoMessage() {}

func (x *UnlinkS3Bucket_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkS3Bucket_Request.ProtoReflect.Descriptor instead.
func (*UnlinkS3Bucket_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{12, 0}
}

func (x *UnlinkS3Bucket_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type UnlinkS3Bucket_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkS3Bucket_Response) Reset() {
	*x = UnlinkS3Bucket_Response{}
	mi := &file_vaults_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkS3Bucket_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkS3Bucket_Response) ProtoMessage() {}

func (x *UnlinkS3Bucket_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkS3Bucket_Response.ProtoReflect.Descriptor instead.
func (*UnlinkS3Bucket_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{12, 1}
}

type SetVaultBinaryStorage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	UseCouchdb    bool                   `protobuf:"varint,2,opt,name=use_couchdb,json=useCouchdb,proto3" json:"use_couchdb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVaultBinaryStorage_Request) Reset() {
	*x = SetVaultBinaryStorage_Request{}
	mi := &file_vaults_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVaultBinaryStorage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVaultBinaryStorage_Request) ProtoMessage() {}

func (x *SetVaultBinaryStorage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVaultBinaryStorage_Request.ProtoReflect.Descriptor instead.
func (*SetVaultBinaryStorage_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{13, 0}
}

func (x *SetVaultBinaryStorage_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *SetVaultBinaryStorage_Request) GetUseCouchdb() bool {
	if x != nil {
		return x.UseCouchdb
	}
	return false
}

type SetVaultBinaryStorage_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVaultBinaryStorage_Response) Reset() {
	*x = SetVaultBinaryStorage_Response{}
	mi := &file_vaults_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVaultBinaryStorage_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVaultBinaryStorage_Response) ProtoMessage() {}

func (x *SetVaultBinaryStorage_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVaultBinaryStorage_Response.ProtoReflect.Descriptor instead.
func (*SetVaultBinaryStorage_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{13, 1}
}

type StartWorkbench_Request struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	VaultId string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// auth_mode: "api_key" or "subscription_login" (see domain.WorkbenchAuthMode). Only
	// "api_key" is currently implemented — any other value fails with
	// user_errors.WorkbenchAuthModeNotImplemented.
	AuthMode      string `protobuf:"bytes,2,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkbench_Request) Reset() {
	*x = StartWorkbench_Request{}
	mi := &file_vaults_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkbench_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkbench_Request) ProtoMessage() {}

func (x *StartWorkbench_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkbench_Request.ProtoReflect.Descriptor instead.
func (*StartWorkbench_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{14, 0}
}

func (x *StartWorkbench_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *StartWorkbench_Request) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

type StartWorkbench_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status: "created"/"running"/"stopped"/"removed" (see domain.WorkbenchStatus).
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AuthMode      string `protobuf:"bytes,2,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkbench_Response) Reset() {
	*x = StartWorkbench_Response{}
	mi := &file_vaults_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkbench_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkbench_Response) ProtoMessage() {}

func (x *StartWorkbench_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkbench_Response.ProtoReflect.Descriptor instead.
func (*StartWorkbench_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{14, 1}
}

func (x *StartWorkbench_Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StartWorkbench_Response) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

type StopWorkbench_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkbench_Request) Reset() {
	*x = StopWorkbench_Request{}
	mi := &file_vaults_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkbench_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkbench_Request) ProtoMessage() {}

func (x *StopWorkbench_Request) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkbench_Request.ProtoReflect.Descriptor instead.
func (*StopWorkbench_Request) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{15, 0}
}

func (x *StopWorkbench_Request) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

type StopWorkbench_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status: "created"/"running"/"stopped"/"removed" (see domain.WorkbenchStatus).
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopWorkbench_Response) Reset() {
	*x = StopWorkbench_Response{}
	mi := &file_vaults_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopWorkbench_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopWorkbench_Response) ProtoMessage() {}

func (x *StopWorkbench_Response) ProtoReflect() protoreflect.Message {
	mi := &file_vaults_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopWorkbench_Response.ProtoReflect.Descriptor instead.
func (*StopWorkbench_Response) Descriptor() ([]byte, []int) {
	return file_vaults_proto_rawDescGZIP(), []int{15, 1}
}

func (x *StopWorkbench_Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_vaults_proto protoreflect.FileDescriptor

const file_vaults_proto_rawDesc = "" +
	"\n" +
	"\fvaults.proto\x12\fartel_vaults\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\"s\n" +
	"\vCreateVault\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1aE\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06db_url\x18\x03 \x01(\tR\x05dbUrl\"\x8f\x02\n" +
	"\bGetVault\x1a\x19\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1a\xe7\x01\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06db_url\x18\x03 \x01(\tR\x05dbUrl\x12$\n" +
	"\x0es3_instance_id\x18\x04 \x01(\tR\fs3InstanceId\x12$\n" +
	"\x0es3_bucket_name\x18\x05 \x01(\tR\fs3BucketName\x12)\n" +
	"\x10workbench_exists\x18\x06 \x01(\bR\x0fworkbenchExists\x12)\n" +
	"\x10workbench_status\x18\a \x01(\tR\x0fworkbenchStatus\"T\n" +
	"\n" +
	"ListVaults\x1a\t\n" +
	"\aRequest\x1a;\n" +
	"\bResponse\x12/\n" +
	"\x06vaults\x18\x01 \x03(\v2\x17.artel_vaults.VaultItemR\x06vaults\"4\n" +
	"\vDeleteVault\x1a\x19\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1a\n" +
	"\n" +
	"\bResponse\"j\n" +
	"\tAddMember\x1aQ\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x1a\n" +
	"\n" +
	"\bResponse\"Y\n" +
	"\fRemoveMember\x1a=\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x1a\n" +
	"\n" +
	"\bResponse\"x\n" +
	"\vListMembers\x1a$\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x1aC\n" +
	"\bResponse\x127\n" +
	"\amembers\x18\x01 \x03(\v2\x1d.artel_vaults.VaultMemberInfoR\amembers\"\x8f\x01\n" +
	"\x10CreateInviteLink\x1a8\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x1aA\n" +
	"\bResponse\x125\n" +
	"\x06invite\x18\x01 \x01(\v2\x1d.artel_vaults.VaultInviteItemR\x06invite\"|\n" +
	"\x0fListInviteLinks\x1a$\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x1aC\n" +
	"\bResponse\x127\n" +
	"\ainvites\x18\x01 \x03(\v2\x1d.artel_vaults.VaultInviteItemR\ainvites\"a\n" +
	"\x10RevokeInviteLink\x1aA\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x1b\n" +
	"\tinvite_id\x18\x02 \x01(\tR\binviteId\x1a\n" +
	"\n" +
	"\bResponse\"V\n" +
	"\fAcceptInvite\x1a\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x1a%\n" +
	"\bResponse\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\"\x87\x01\n" +
	"\fLinkS3Bucket\x1ak\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12$\n" +
	"\x0es3_instance_id\x18\x02 \x01(\tR\fs3InstanceId\x12\x1f\n" +
	"\vbucket_name\x18\x03 \x01(\tR\n" +
	"bucketName\x1a\n" +
	"\n" +
	"\bResponse\"B\n" +
	"\x0eUnlinkS3Bucket\x1a$\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x1a\n" +
	"\n" +
	"\bResponse\"j\n" +
	"\x15SetVaultBinaryStorage\x1aE\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x1f\n" +
	"\vuse_couchdb\x18\x02 \x01(\bR\n" +
	"useCouchdb\x1a\n" +
	"\n" +
	"\bResponse\"\x94\x01\n" +
	"\x0eStartWorkbench\x1aA\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x1b\n" +
	"\tauth_mode\x18\x02 \x01(\tR\bauthMode\x1a?\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tauth_mode\x18\x02 \x01(\tR\bauthMode\"Y\n" +
	"\rStopWorkbench\x1a$\n" +
	"\aRequest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xfc\x01\n" +
	"\tVaultItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06db_url\x18\x03 \x01(\tR\x05dbUrl\x12/\n" +
	"\x13livesync_passphrase\x18\x04 \x01(\tR\x12livesyncPassphrase\x12$\n" +
	"\x0es3_instance_id\x18\x05 \x01(\tR\fs3InstanceId\x12$\n" +
	"\x0es3_bucket_name\x18\x06 \x01(\tR\fs3BucketName\x127\n" +
	"\x18use_couchdb_for_binaries\x18\a \x01(\bR\x15useCouchdbForBinaries\"\x80\x01\n" +
	"\x0fVaultMemberInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"\x9f\x01\n" +
	"\x0fVaultInviteItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bvault_id\x18\x02 \x01(\tR\avaultId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x18\n" +
	"\arevoked\x18\x05 \x01(\bR\arevoked\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2\xf7\x0f\n" +
	"\tVaultsAPI\x12s\n" +
	"\vCreateVault\x12!.artel_vaults.CreateVault.Request\x1a\".artel_vaults.CreateVault.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/vaults/create\x12g\n" +
	"\bGetVault\x12\x1e.artel_vaults.GetVault.Request\x1a\x1f.artel_vaults.GetVault.Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/vaults/get\x12n\n" +
	"\n" +
	"ListVaults\x12 .artel_vaults.ListVaults.Request\x1a!.artel_vaults.ListVaults.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/vaults/list\x12s\n" +
	"\vDeleteVault\x12!.artel_vaults.DeleteVault.Request\x1a\".artel_vaults.DeleteVault.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/vaults/delete\x12r\n" +
	"\tAddMember\x12\x1f.artel_vaults.AddMember.Request\x1a .artel_vaults.AddMember.Response\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/vaults/members/add\x12~\n" +
	"\fRemoveMember\x12\".artel_vaults.RemoveMember.Request\x1a#.artel_vaults.RemoveMember.Response\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/vaults/members/remove\x12y\n" +
	"\vListMembers\x12!.artel_vaults.ListMembers.Request\x1a\".artel_vaults.ListMembers.Response\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/vaults/members/list\x12\x8a\x01\n" +
	"\x10CreateInviteLink\x12&.artel_vaults.CreateInviteLink.Request\x1a'.artel_vaults.CreateInviteLink.Response\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/vaults/invites/create\x12\x85\x01\n" +
	"\x0fListInviteLinks\x12%.artel_vaults.ListInviteLinks.Request\x1a&.artel_vaults.ListInviteLinks.Response\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/vaults/invites/list\x12\x8a\x01\n" +
	"\x10RevokeInviteLink\x12&.artel_vaults.RevokeInviteLink.Request\x1a'.artel_vaults.RevokeInviteLink.Response\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/vaults/invites/revoke\x12t\n" +
	"\fAcceptInvite\x12\".artel_vaults.AcceptInvite.Request\x1a#.artel_vaults.AcceptInvite.Response\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/vaults/join\x12w\n" +
	"\fLinkS3Bucket\x12\".artel_vaults.LinkS3Bucket.Request\x1a#.artel_vaults.LinkS3Bucket.Response\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/vaults/s3/link\x12\x7f\n" +
	"\x0eUnlinkS3Bucket\x12$.artel_vaults.UnlinkS3Bucket.Request\x1a%.artel_vaults.UnlinkS3Bucket.Response\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/vaults/s3/unlink\x12\x99\x01\n" +
	"\x15SetVaultBinaryStorage\x12+.artel_vaults.SetVaultBinaryStorage.Request\x1a,.artel_vaults.SetVaultBinaryStorage.Response\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/vaults/binary-storage\x12\x85\x01\n" +
	"\x0eStartWorkbench\x12$.artel_vaults.StartWorkbench.Request\x1a%.artel_vaults.StartWorkbench.Response\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/vaults/workbench/start\x12\x81\x01\n" +
	"\rStopWorkbench\x12#.artel_vaults.StopWorkbench.Request\x1a$.artel_vaults.StopWorkbench.Response\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/vaults/workbench/stopB\x1a\x92\x82\x19\n" +
	"@artel/apiZ\n" +
	"/artel_apib\x06proto3"

var (
	file_vaults_proto_rawDescOnce sync.Once
	file_vaults_proto_rawDescData []byte
)

func file_vaults_proto_rawDescGZIP() []byte {
	file_vaults_proto_rawDescOnce.Do(func() {
		file_vaults_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaults_proto_rawDesc), len(file_vaults_proto_rawDesc)))
	})
	return file_vaults_proto_rawDescData
}

var file_vaults_proto_msgTypes = make([]protoimpl.MessageInfo, 51)
var file_vaults_proto_goTypes = []any{
	(*CreateVault)(nil),                    // 0: artel_vaults.CreateVault
	(*GetVault)(nil),                       // 1: artel_vaults.GetVault
	(*ListVaults)(nil),                     // 2: artel_vaults.ListVaults
	(*DeleteVault)(nil),                    // 3: artel_vaults.DeleteVault
	(*AddMember)(nil),                      // 4: artel_vaults.AddMember
	(*RemoveMember)(nil),                   // 5: artel_vaults.RemoveMember
	(*ListMembers)(nil),                    // 6: artel_vaults.ListMembers
	(*CreateInviteLink)(nil),               // 7: artel_vaults.CreateInviteLink
	(*ListInviteLinks)(nil),                // 8: artel_vaults.ListInviteLinks
	(*RevokeInviteLink)(nil),               // 9: artel_vaults.RevokeInviteLink
	(*AcceptInvite)(nil),                   // 10: artel_vaults.AcceptInvite
	(*LinkS3Bucket)(nil),                   // 11: artel_vaults.LinkS3Bucket
	(*UnlinkS3Bucket)(nil),                 // 12: artel_vaults.UnlinkS3Bucket
	(*SetVaultBinaryStorage)(nil),          // 13: artel_vaults.SetVaultBinaryStorage
	(*StartWorkbench)(nil),                 // 14: artel_vaults.StartWorkbench
	(*StopWorkbench)(nil),                  // 15: artel_vaults.StopWorkbench
	(*VaultItem)(nil),                      // 16: artel_vaults.VaultItem
	(*VaultMemberInfo)(nil),                // 17: artel_vaults.VaultMemberInfo
	(*VaultInviteItem)(nil),                // 18: artel_vaults.VaultInviteItem
	(*CreateVault_Request)(nil),            // 19: artel_vaults.CreateVault.Request
	(*CreateVault_Response)(nil),           // 20: artel_vaults.CreateVault.Response
	(*GetVault_Request)(nil),               // 21: artel_vaults.GetVault.Request
	(*GetVault_Response)(nil),              // 22: artel_vaults.GetVault.Response
	(*ListVaults_Request)(nil),             // 23: artel_vaults.ListVaults.Request
	(*ListVaults_Response)(nil),            // 24: artel_vaults.ListVaults.Response
	(*DeleteVault_Request)(nil),            // 25: artel_vaults.DeleteVault.Request
	(*DeleteVault_Response)(nil),           // 26: artel_vaults.DeleteVault.Response
	(*AddMember_Request)(nil),              // 27: artel_vaults.AddMember.Request
	(*AddMember_Response)(nil),             // 28: artel_vaults.AddMember.Response
	(*RemoveMember_Request)(nil),           // 29: artel_vaults.RemoveMember.Request
	(*RemoveMember_Response)(nil),          // 30: artel_vaults.RemoveMember.Response
	(*ListMembers_Request)(nil),            // 31: artel_vaults.ListMembers.Request
	(*ListMembers_Response)(nil),           // 32: artel_vaults.ListMembers.Response
	(*CreateInviteLink_Request)(nil),       // 33: artel_vaults.CreateInviteLink.Request
	(*CreateInviteLink_Response)(nil),      // 34: artel_vaults.CreateInviteLink.Response
	(*ListInviteLinks_Request)(nil),        // 35: artel_vaults.ListInviteLinks.Request
	(*ListInviteLinks_Response)(nil),       // 36: artel_vaults.ListInviteLinks.Response
	(*RevokeInviteLink_Request)(nil),       // 37: artel_vaults.RevokeInviteLink.Request
	(*RevokeInviteLink_Response)(nil),      // 38: artel_vaults.RevokeInviteLink.Response
	(*AcceptInvite_Request)(nil),           // 39: artel_vaults.AcceptInvite.Request
	(*AcceptInvite_Response)(nil),          // 40: artel_vaults.AcceptInvite.Response
	(*LinkS3Bucket_Request)(nil),           // 41: artel_vaults.LinkS3Bucket.Request
	(*LinkS3Bucket_Response)(nil),          // 42: artel_vaults.LinkS3Bucket.Response
	(*UnlinkS3Bucket_Request)(nil),         // 43: artel_vaults.UnlinkS3Bucket.Request
	(*UnlinkS3Bucket_Response)(nil),        // 44: artel_vaults.UnlinkS3Bucket.Response
	(*SetVaultBinaryStorage_Request)(nil),  // 45: artel_vaults.SetVaultBinaryStorage.Request
	(*SetVaultBinaryStorage_Response)(nil), // 46: artel_vaults.SetVaultBinaryStorage.Response
	(*StartWorkbench_Request)(nil),         // 47: artel_vaults.StartWorkbench.Request
	(*StartWorkbench_Response)(nil),        // 48: artel_vaults.StartWorkbench.Response
	(*StopWorkbench_Request)(nil),          // 49: artel_vaults.StopWorkbench.Request
	(*StopWorkbench_Response)(nil),         // 50: artel_vaults.StopWorkbench.Response
}
var file_vaults_proto_depIdxs = []int32{
	16, // 0: artel_vaults.ListVaults.Response.vaults:type_name -> artel_vaults.VaultItem
	17, // 1: artel_vaults.ListMembers.Response.members:type_name -> artel_vaults.VaultMemberInfo
	18, // 2: artel_vaults.CreateInviteLink.Response.invite:type_name -> artel_vaults.VaultInviteItem
	18, // 3: artel_vaults.ListInviteLinks.Response.invites:type_name -> artel_vaults.VaultInviteItem
	19, // 4: artel_vaults.VaultsAPI.CreateVault:input_type -> artel_vaults.CreateVault.Request
	21, // 5: artel_vaults.VaultsAPI.GetVault:input_type -> artel_vaults.GetVault.Request
	23, // 6: artel_vaults.VaultsAPI.ListVaults:input_type -> artel_vaults.ListVaults.Request
	25, // 7: artel_vaults.VaultsAPI.DeleteVault:input_type -> artel_vaults.DeleteVault.Request
	27, // 8: artel_vaults.VaultsAPI.AddMember:input_type -> artel_vaults.AddMember.Request
	29, // 9: artel_vaults.VaultsAPI.RemoveMember:input_type -> artel_vaults.RemoveMember.Request
	31, // 10: artel_vaults.VaultsAPI.ListMembers:input_type -> artel_vaults.ListMembers.Request
	33, // 11: artel_vaults.VaultsAPI.CreateInviteLink:input_type -> artel_vaults.CreateInviteLink.Request
	35, // 12: artel_vaults.VaultsAPI.ListInviteLinks:input_type -> artel_vaults.ListInviteLinks.Request
	37, // 13: artel_vaults.VaultsAPI.RevokeInviteLink:input_type -> artel_vaults.RevokeInviteLink.Request
	39, // 14: artel_vaults.VaultsAPI.AcceptInvite:input_type -> artel_vaults.AcceptInvite.Request
	41, // 15: artel_vaults.VaultsAPI.LinkS3Bucket:input_type -> artel_vaults.LinkS3Bucket.Request
	43, // 16: artel_vaults.VaultsAPI.UnlinkS3Bucket:input_type -> artel_vaults.UnlinkS3Bucket.Request
	45, // 17: artel_vaults.VaultsAPI.SetVaultBinaryStorage:input_type -> artel_vaults.SetVaultBinaryStorage.Request
	47, // 18: artel_vaults.VaultsAPI.StartWorkbench:input_type -> artel_vaults.StartWorkbench.Request
	49, // 19: artel_vaults.VaultsAPI.StopWorkbench:input_type -> artel_vaults.StopWorkbench.Request
	20, // 20: artel_vaults.VaultsAPI.CreateVault:output_type -> artel_vaults.CreateVault.Response
	22, // 21: artel_vaults.VaultsAPI.GetVault:output_type -> artel_vaults.GetVault.Response
	24, // 22: artel_vaults.VaultsAPI.ListVaults:output_type -> artel_vaults.ListVaults.Response
	26, // 23: artel_vaults.VaultsAPI.DeleteVault:output_type -> artel_vaults.DeleteVault.Response
	28, // 24: artel_vaults.VaultsAPI.AddMember:output_type -> artel_vaults.AddMember.Response
	30, // 25: artel_vaults.VaultsAPI.RemoveMember:output_type -> artel_vaults.RemoveMember.Response
	32, // 26: artel_vaults.VaultsAPI.ListMembers:output_type -> artel_vaults.ListMembers.Response
	34, // 27: artel_vaults.VaultsAPI.CreateInviteLink:output_type -> artel_vaults.CreateInviteLink.Response
	36, // 28: artel_vaults.VaultsAPI.ListInviteLinks:output_type -> artel_vaults.ListInviteLinks.Response
	38, // 29: artel_vaults.VaultsAPI.RevokeInviteLink:output_type -> artel_vaults.RevokeInviteLink.Response
	40, // 30: artel_vaults.VaultsAPI.AcceptInvite:output_type -> artel_vaults.AcceptInvite.Response
	42, // 31: artel_vaults.VaultsAPI.LinkS3Bucket:output_type -> artel_vaults.LinkS3Bucket.Response
	44, // 32: artel_vaults.VaultsAPI.UnlinkS3Bucket:output_type -> artel_vaults.UnlinkS3Bucket.Response
	46, // 33: artel_vaults.VaultsAPI.SetVaultBinaryStorage:output_type -> artel_vaults.SetVaultBinaryStorage.Response
	48, // 34: artel_vaults.VaultsAPI.StartWorkbench:output_type -> artel_vaults.StartWorkbench.Response
	50, // 35: artel_vaults.VaultsAPI.StopWorkbench:output_type -> artel_vaults.StopWorkbench.Response
	20, // [20:36] is the sub-list for method output_type
	4,  // [4:20] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_vaults_proto_init() }
func file_vaults_proto_init() {
	if File_vaults_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaults_proto_rawDesc), len(file_vaults_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   51,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaults_proto_goTypes,
		DependencyIndexes: file_vaults_proto_depIdxs,
		MessageInfos:      file_vaults_proto_msgTypes,
	}.Build()
	File_vaults_proto = out.File
	file_vaults_proto_goTypes = nil
	file_vaults_proto_depIdxs = nil
}
