// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"
	"encoding/hex"
	"net/http"

	"github.com/rs/zerolog/log"
	"go.redsock.ru/rerrors"

	pb "github.com/ruf-dev/artel/internal/api/server/artel_api"
	"github.com/ruf-dev/artel/internal/middleware"
	repopg "github.com/ruf-dev/artel/internal/repository/pg"
	svcv1 "github.com/ruf-dev/artel/internal/service/v1"
	"github.com/ruf-dev/artel/internal/transport"
	"github.com/ruf-dev/artel/internal/transport/auth_api"
	"github.com/ruf-dev/artel/internal/transport/couch_instances_api"
	"github.com/ruf-dev/artel/internal/transport/email_accounts_api"
	"github.com/ruf-dev/artel/internal/transport/mcp_api"
	"github.com/ruf-dev/artel/internal/transport/mcp_keys_api"
	"github.com/ruf-dev/artel/internal/transport/ui"
	"github.com/ruf-dev/artel/internal/transport/vaults_api"
)

type Custom struct {
	Transport *transport.ServersManager
}

func (c *Custom) Init(a *App) error {
	encKeyHex := a.Cfg.Environment.CredsEncryptionKey
	encKey, err := hex.DecodeString(encKeyHex)
	if err != nil {
		return rerrors.Wrap(err, "error decoding creds_encryption_key")
	}

	repo := repopg.New(a.Postgres, encKey)

	services, err := svcv1.New(repo, a.Cfg.Environment)
	if err != nil {
		return rerrors.Wrap(err, "init services")
	}

	c.Transport, err = transport.NewServerManager(a.Ctx, a.MASTER)
	if err != nil {
		return rerrors.Wrap(err, "error creating server manager")
	}

	vaultsImpl := vaults_api.NewVaultsImpl(services.Vault)
	authImpl := auth_api.NewAuthImpl(services.Auth, a.Cfg.Environment.TelegramClientID)
	couchInstancesImpl := couch_instances_api.NewCouchInstancesImpl(services.CouchInstance)
	mcpKeysImpl := mcp_keys_api.NewMcpKeysImpl(services.McpService())
	emailAccountsImpl := email_accounts_api.NewEmailAccountsImpl(services.EmailService())
	mcpHandler := mcp_api.NewMcpHandler(services.McpService(), services.EmailService())
	oauthHandler := mcp_api.NewOAuthHandler(services.Auth, services.Vault, services.McpService(), repo.PendingAuthCodes())

	c.Transport.AddServerOption(
		middleware.GrpcAuthInterceptor(services,
			middleware.WithIgnoredPathAuthOption(
				pb.AuthAPI_Register_FullMethodName,
				pb.AuthAPI_Login_FullMethodName,
				pb.AuthAPI_GetConfig_FullMethodName,
			),
		),
		middleware.LogInterceptor(),
		middleware.PanicInterceptor(),
	)
	c.Transport.AddImplementation(authImpl, vaultsImpl, couchInstancesImpl, mcpKeysImpl, emailAccountsImpl)

	c.Transport.AddHttpHandler("/mcp", mcpHandler)
	c.Transport.AddHttpHandler("/.well-known/oauth-authorization-server", http.HandlerFunc(oauthHandler.WellKnown))
	c.Transport.AddHttpHandler("/.well-known/oauth-protected-resource", http.HandlerFunc(oauthHandler.ServeProtectedResourceMeta))
	c.Transport.AddHttpHandler("/.well-known/oauth-protected-resource/mcp", http.HandlerFunc(oauthHandler.ServeProtectedResourceMeta))
	c.Transport.AddHttpHandler("/register", http.HandlerFunc(oauthHandler.ServeRegistration))
	c.Transport.AddHttpHandler("/oauth/login", http.HandlerFunc(oauthHandler.ServeOAuthLogin))
	c.Transport.AddHttpHandler("/oauth/vaults", http.HandlerFunc(oauthHandler.ServeOAuthVaults))
	c.Transport.AddHttpHandler("/oauth/vault", http.HandlerFunc(oauthHandler.ServeOAuthVault))
	c.Transport.AddHttpHandler("/token", http.HandlerFunc(oauthHandler.ServeToken))
	c.Transport.AddHttpHandler("/", ui.NewHandler())

	return nil
}

// Start - launch custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Start(ctx context.Context) error {
	log.Info().Msg("starting server")

	err := c.Transport.Start()
	if err != nil {
		return rerrors.Wrap(err, "error starting server")
	}

	return nil
}

// Stop - gracefully stop custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Stop() error {
	err := c.Transport.Stop()
	if err != nil {
		return rerrors.Wrap(err, "error stopping server")
	}
	return nil
}
