// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"
	"encoding/hex"

	"github.com/rs/zerolog/log"
	"go.redsock.ru/rerrors"

	"github.com/ruf-dev/artel/internal/api/server/artel_api_impl"
	repopg "github.com/ruf-dev/artel/internal/repository/pg"
	svcv1 "github.com/ruf-dev/artel/internal/service/v1"
	"github.com/ruf-dev/artel/internal/transport"
)

type Custom struct {
	Transport *transport.ServersManager
}

func (c *Custom) Init(a *App) error {
	encKeyHex := a.Cfg.Environment.CredsEncryptionKey
	encKey, err := hex.DecodeString(encKeyHex)
	if err != nil {
		return rerrors.Wrap(err, "error decoding creds_encryption_key")
	}

	repo := repopg.New(a.Postgres, encKey)

	services := svcv1.New(repo)

	c.Transport, err = transport.NewServerManager(a.Ctx, a.MASTER)
	if err != nil {
		return rerrors.Wrap(err, "error creating server manager")
	}

	vaultsImpl := artel_api_impl.NewVaultsImpl(services.Vault)
	usersImpl := artel_api_impl.NewUsersImpl(services.User)

	c.Transport.AddImplementation(vaultsImpl, usersImpl)

	return nil
}

// Start - launch custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Start(ctx context.Context) error {
	log.Info().Msg("starting server")

	err := c.Transport.Start()
	if err != nil {
		return rerrors.Wrap(err, "error starting server")
	}

	return nil
}

// Stop - gracefully stop custom handlers
// Even if you won't use it keep it for proper work
func (c *Custom) Stop() error {
	err := c.Transport.Stop()
	if err != nil {
		return rerrors.Wrap(err, "error stopping server")
	}
	return nil
}
