app_info:
    name: github.com/ruf-dev/artel
    version: v0.0.12
    startup_duration: 10s
data_sources:
    - resource_name: postgres
      migrations_folder: ./migrations
      host: localhost
      port: 5432
      user: artel
      pwd: ""
      name: artel
      ssl_mode: ""
servers:
    1551:
        /{GRPC}:
            module: github.com/ruf-dev/artel
            gateway: /api
environment:
    - name: creds_encryption_key
      type: string
      value: ""
    - name: log_format
      type: string
      enum: [JSON, TEXT]
      value: TEXT
    - name: log_level
      type: string
      enum: [Trace, Debug, Info, Warn, Error, Fatal, Panic]
      value: Info
    - name: telegram_client_id
      type: string
      value: "8719705888"
