#!/usr/bin/with-contenv sh
set -e

mkdir -p /data/secrets

if [ ! -f /data/secrets/creds_encryption_key ]; then
  openssl rand -hex 32 > /data/secrets/creds_encryption_key
fi

chown -R app:app /data/secrets
