### Add email account
POST {{artel_url}}/api/email-accounts/add
Content-Type: application/json
Authorization: {{auth_token}}

{
  "email": "user@gmail.com",
  "imapHost": "imap.gmail.com",
  "imapPort": 993,
  "smtpHost": "smtp.gmail.com",
  "smtpPort": 587,
  "password": "secret"
}

### List email accounts
POST {{artel_url}}/api/email-accounts/list
Authorization: {{auth_token}}
Content-Type: application/json

{

}

### Delete email account
DELETE {{artel_url}}/api/email-accounts/{{email_account_id}}
Authorization: {{auth_token}}


### Suggest email
POST {{artel_url}}/api/email-accounts/list_suggestions
Content-Type: application/json

{

}