// Code generated by RedSock CLI. DO NOT EDIT.

package config

import (
	"flag"
	"net/url"

	"go.redsock.ru/rerrors"
	"go.vervstack.ru/matreshka/pkg/matreshka"
)

var ErrAlreadyLoaded = rerrors.New("config already loaded")

type Config struct {
	AppInfo matreshka.AppInfo

	Environment EnvironmentConfig
	Overrides   matreshka.ServiceDiscovery
	CouchDB     CouchDB

	MatreshkaConfig matreshka.AppConfig
}

var defaultConfig Config

const (
	devConfigPath  = "./config/dev.yaml"
	prodConfigPath = "./config/config.yaml"
)

func Init() (Config, error) {
	if defaultConfig.AppInfo.Name != "" {
		return defaultConfig, ErrAlreadyLoaded
	}

	var cfgPath string
	var isDevBuild bool

	flag.StringVar(&cfgPath, "config", "", "Path to configuration file")
	flag.BoolVar(&isDevBuild, "dev", false, "Flag turns on a dev config at ./config/dev.yaml")
	flag.Parse()

	var configsPaths []string

	if cfgPath != "" {
		configsPaths = append(configsPaths, cfgPath)
	}

	if isDevBuild {
		configsPaths = append(configsPaths, devConfigPath)
	}
	configsPaths = append(configsPaths, prodConfigPath)

	var err error
	defaultConfig, err = Load(configsPaths...)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error loading config")
	}

	return defaultConfig, nil
}

func Load(configsPaths ...string) (Config, error) {
	var err error
	defaultConfig.MatreshkaConfig, err = matreshka.ReadConfigs(configsPaths...)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error reading matreshka config")
	}

	defaultConfig.AppInfo = defaultConfig.MatreshkaConfig.AppInfo
	defaultConfig.Overrides = defaultConfig.MatreshkaConfig.ServiceDiscovery

	err = defaultConfig.MatreshkaConfig.Environment.
		ParseToStruct(&defaultConfig.Environment)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error parsing environment config")
	}

	defaultConfig.CouchDB, err = parseCouchDBConfig(defaultConfig.Environment.CouchdbUrl)
	if err != nil {
		return defaultConfig, rerrors.Wrap(err, "error parsing couchdb config")
	}

	return defaultConfig, nil
}

func parseCouchDBConfig(rawURL string) (CouchDB, error) {
	u, err := url.Parse(rawURL)
	if err != nil {
		return CouchDB{}, rerrors.Wrap(err, "invalid couchdb url")
	}

	var c CouchDB
	if u.User != nil {
		c.User = u.User.Username()
		c.Password, _ = u.User.Password()
		u.User = nil
	}
	c.BaseURL = u.String()

	return c, nil
}
