syntax = "proto3";

package artel_users;

import "google/api/annotations.proto";

option go_package = "/artel_api";

service AccountsAPI {
  rpc CreateAccount(CreateAccount.Request) returns (CreateAccount.Response) {
    option (google.api.http) = {
      post: "/api/users/add"
      body: "*"
    };
  };
  rpc GetUser(GetUser.Request) returns (GetUser.Response) {
    option (google.api.http) = {
      get: "/api/users/{username}"
    };
  };
  rpc UpdateUser(UpdateUser.Request) returns (UpdateUser.Response) {
    option (google.api.http) = {
      put: "/api/users/{username}"
      body: "*"
    };
  };
  rpc DeleteUser(DeleteUser.Request) returns (DeleteUser.Response) {
    option (google.api.http) = {
      delete: "/api/users/{username}"
    };
  };
}

message CreateAccount {
  message Request {
    string username = 1;
    repeated string roles = 3;
  }
  message Response {
    string username = 1;
    repeated string roles = 2;
  }
}

message GetUser {
  message Request {
    string username = 1;
  }
  message Response {
    string username = 1;
    repeated string roles = 2;
  }
}

message UpdateUser {
  message Request {
    string username = 1;
    string password = 2;
    repeated string roles = 3;
  }
  message Response {
    string username = 1;
    repeated string roles = 2;
  }
}

message DeleteUser {
  message Request {
    string username = 1;
  }
  message Response {
    bool ok = 1;
  }
}