syntax = "proto3";

package artel_auth;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "npm.proto";

option go_package = "/artel_api";
option (npm_package) = "@artel/api";

service AuthAPI {
  rpc Register(Register.Request) returns (Register.Response) {
    option (google.api.http) = {
      post: "/api/auth/register"
      body: "*"
    };
  };
  rpc Login(Login.Request) returns (Login.Response) {
    option (google.api.http) = {
      post: "/api/auth/login"
      body: "*"
    };
  };
  rpc Logout(Logout.Request) returns (Logout.Response) {
    option (google.api.http) = {
      post: "/api/auth/logout"
      body: "*"
    };
  };
  rpc Refresh(Refresh.Request) returns (Refresh.Response) {
    option (google.api.http) = {
      post: "/api/auth/refresh"
      body: "*"
    };
  };
  rpc GetConfig(GetConfig.Request) returns (GetConfig.Response) {
    option (google.api.http) = {
      post: "/api/auth/config"
      body: "*"
    };
  };
  rpc GetMe(GetMe.Request) returns (GetMe.Response) {
    option (google.api.http) = {
      post: "/api/auth/me"
      body: "*"
    };
  };
}

message PasswordCredentials {
  string email    = 1;
  string password = 2;
}

message TelegramCredentials {
  string id_token = 1;
}

message Register {
  message Request {
    string email    = 1;
    string password = 2;
  }
  message Response {
    string id    = 1;
    string email = 2;
  }
}

message Login {
  message Request {
    oneof method {
      PasswordCredentials password  = 1;
      TelegramCredentials telegram  = 2;
    }
  }
  message Response {
    string                    token               = 1;
    google.protobuf.Timestamp expires_at          = 2;
    string                    refresh_token       = 3;
    google.protobuf.Timestamp refresh_expires_at  = 4;
  }
}

message Logout {
  message Request {}
  message Response {}
}

message Refresh {
  message Request {
    string refresh_token = 1;
  }
  message Response {
    string                    token              = 1;
    google.protobuf.Timestamp expires_at         = 2;
    string                    refresh_token      = 3;
    google.protobuf.Timestamp refresh_expires_at = 4;
  }
}

message GetConfig {
  message Request {}
  message Response {
    string telegram_client_id = 1;
    bool is_s3_available = 2;
    bool no_auth_enabled = 3;
  }
}

message Permissions {
  bool is_administrator = 1;
  bool has_emails = 2;
  bool has_task_trackers = 3;
  bool has_notes = 4;
}

message GetMe {
  message Request {}
  message Response {
    string      id          = 1;
    string      username    = 2;
    string      email       = 3;
    Permissions permissions = 4;
    string      photo_url   = 5;
  }
}
