syntax = "proto3";

package artel_couch;

import "google/api/annotations.proto";
import "npm.proto";

option go_package = "/artel_api";
option (npm_package) = "@artel/api";

service CouchInstancesAPI {
  rpc RegisterCouchInstance(RegisterCouchInstance.Request) returns (RegisterCouchInstance.Response) {
    option (google.api.http) = {
      post: "/api/couch/add"
      body: "*"
    };
  };
  rpc GetCouchInstance(GetCouchInstance.Request) returns (GetCouchInstance.Response) {
    option (google.api.http) = {
      post: "/api/couch/get"
      body: "*"
    };
  };
  rpc ListCouchInstances(ListCouchInstances.Request) returns (ListCouchInstances.Response) {
    option (google.api.http) = {
      post: "/api/couch/list"
      body: "*"
    };
  };
  rpc UpdateCouchInstance(UpdateCouchInstance.Request) returns (UpdateCouchInstance.Response) {
    option (google.api.http) = {
      post: "/api/couch/update"
      body: "*"
    };
  };
  rpc DeleteCouchInstance(DeleteCouchInstance.Request) returns (DeleteCouchInstance.Response) {
    option (google.api.http) = {
      post: "/api/couch/delete"
      body: "*"
    };
  };
  rpc SetupCouchInstance(SetupCouchInstance.Request) returns (SetupCouchInstance.Response) {
    option (google.api.http) = {
      post: "/api/couch/setup"
      body: "*"
    };
  };
  rpc GetCouchInstanceStatus(GetCouchInstanceStatus.Request) returns (GetCouchInstanceStatus.Response) {
    option (google.api.http) = {
      post: "/api/couch/status"
      body: "*"
    };
  };
}

message RegisterCouchInstance {
  message Request {
    string url = 1;
    string username = 2;
    string password = 3;
  }
  message Response {
    string id = 1;
  }
}

message GetCouchInstance {
  message Request {
    string id = 1;
  }
  message Response {
    string id = 1;
    string url = 2;
    string username = 3;
    string created_at = 4;
  }
}

message ListCouchInstances {
  message Request {}
  message Response {
    repeated GetCouchInstance.Response instances = 1;
  }
}

message UpdateCouchInstance {
  message Request {
    string id       = 1;
    string url      = 2;
    string username = 3;
    string password = 4;
  }
  message Response {}
}

message DeleteCouchInstance {
  message Request {
    string id = 1;
  }
  message Response {}
}

message SetupCouchInstance {
  message Request {
    string id = 1;
  }
  message Response {}
}

message GetCouchInstanceStatus {
  message Request {
    string id = 1;
  }
  message Response {
    bool cluster_mode_enabled      = 1;
    bool users_db_initialized      = 2;
    bool replicator_db_initialized = 3;
  }
}
