syntax = "proto3";

package artel_api;

import "google/api/annotations.proto";

option go_package = "/artel_api";

service EmailAccountsAPI {
    rpc AddEmailAccount(AddEmailAccount.Request) returns (AddEmailAccount.Response) {
        option (google.api.http) = {
            post: "/api/email-accounts/add"
            body: "*"
        };
    }

    rpc ListEmailAccounts(ListEmailAccounts.Request) returns (ListEmailAccounts.Response) {
        option (google.api.http) = {
            post: "/api/email-accounts/list"
            body: "*"
        };
    }

    rpc DeleteEmailAccount(DeleteEmailAccount.Request) returns (DeleteEmailAccount.Response) {
        option (google.api.http) = {
            post: "/api/email-accounts/delete"
            body: "*"
        };
    }

    rpc ListMailServerSuggestions(ListMailServerSuggestions.Request) returns (ListMailServerSuggestions.Response) {
        option (google.api.http) = {
            post: "/api/email-accounts/list_suggestions"
            body: "*"
        };
    }
}

message EmailAccountInfo {
    string id         = 1;
    string email      = 2;
    string imap_host  = 3;
    int32  imap_port  = 4;
    string smtp_host  = 5;
    int32  smtp_port  = 6;
    string created_at = 7;
}

message AddEmailAccount {
    message Request {
        string email     = 1;
        string imap_host = 2;
        int32  imap_port = 3;
        string smtp_host = 4;
        int32  smtp_port = 5;
        string password  = 6;
    }
    message Response {
        EmailAccountInfo account = 1;
    }
}

message ListEmailAccounts {
    message Request {}
    message Response {
        repeated EmailAccountInfo accounts = 1;
    }
}

message DeleteEmailAccount {
    message Request {
        string id = 1;
    }
    message Response {}
}

message MailServerSuggestionInfo {
    string domain    = 1;
    string smtp      = 2;
    int32  smtp_port = 3;
    string imap      = 4;
    int32  imap_port = 5;
}

message ListMailServerSuggestions {
    message Request  { string domain = 1; }
    message Response { repeated MailServerSuggestionInfo suggestions = 1; }
}
