syntax = "proto3";

package artel_vaults;

import "google/api/annotations.proto";
import "npm.proto";

option go_package = "/artel_api";
option (npm_package) = "@artel/api";

service VaultsAPI {
  rpc CreateVault(CreateVault.Request) returns (CreateVault.Response) {
    option (google.api.http) = {
      post: "/api/vaults/create"
      body: "*"
    };
  };
  rpc GetVault(GetVault.Request) returns (GetVault.Response) {
    option (google.api.http) = {
      get: "/api/vaults/{id}"
    };
  };
  rpc ListVaults(ListVaults.Request) returns (ListVaults.Response) {
    option (google.api.http) = {
      post: "/api/vaults/list",
      body: "*"
    };
  };
  rpc DeleteVault(DeleteVault.Request) returns (DeleteVault.Response) {
    option (google.api.http) = {
      post: "/api/vaults/{id}/delete"
    };
  };
  rpc AddMember(AddMember.Request) returns (AddMember.Response) {
    option (google.api.http) = {
      post: "/api/vaults/{vault_id}/members"
      body: "*"
    };
  };
  rpc RemoveMember(RemoveMember.Request) returns (RemoveMember.Response) {
    option (google.api.http) = {
      delete: "/api/vaults/{vault_id}/members/{user_id}"
    };
  };
}

message CreateVault {
  message Request {
    string name = 1;
  }
  message Response {
    string id = 1;
    string name = 2;
    string db_url = 3;
  }
}

message GetVault {
  message Request {
    string id = 1;
  }
  message Response {
    string id = 1;
    string name = 2;
    string db_url = 3;
  }
}

message ListVaults {
  message Request {}
  message Response {
    repeated VaultItem vaults = 1;
  }
}

message DeleteVault {
  message Request {
    string id = 1;
  }
  message Response {}
}

message AddMember {
  message Request {
    string vault_id = 1;
    string user_id = 2;
  }
  message Response {}
}

message RemoveMember {
  message Request {
    string vault_id = 1;
    string user_id = 2;
  }
  message Response {}
}

message VaultItem {
  string id = 1;
  string name = 2;
  string db_url = 3;
}
